// 1 frozen pages: the /jobs page, as Contentful held them the day
// they were taken out of it. This file IS the source — there is no CMS read
// behind it any more, so a copy change is an edit here and a deploy.
//
// Generated by scripts/freeze-cms.mts. Regenerating overwrites hand edits, so
// once you start editing the copy here, stop regenerating: the CMS entries are
// no longer maintained. Imagery lives in public/images/cms, downloaded with it.
import type { CareersPage } from "./careers";

export const FROZEN_CAREERS_PAGE: CareersPage = {
  "title": "Join us at Assembly",
  "description": "We’re building the tools that power the next generation of professional services firms.",
  "banner": {
    "url": "/images/cms/2JK8XYUEnhcwvnoKMJST8Y-img_3615.webp",
    "alt": "Team pic from Colombia",
    "width": 2400,
    "height": 1187
  },
  "sectionTitles": {
    "roles": "Roles",
    "media": "Team writing & media",
    "benefits": "Benefits"
  },
  "benefits": [
    {
      "title": "Equity",
      "description": "We want you to reap the benefits of the upside you create in the company."
    },
    {
      "title": "Health insurance",
      "description": "Tier 1 Blue Cross plan with 100% coverage for you and 50% coverage for dependents."
    },
    {
      "title": "Flexible PTO",
      "description": "We recommend ~20 days of vacation per year. You can take whatever days you want."
    },
    {
      "title": "International offsites",
      "description": "We do team off-sites twice per year. In July, we met up in Istanbul."
    },
    {
      "title": "Sick leave",
      "description": "Take the time you need to recharge! We want everyone feeling their best at work."
    },
    {
      "title": "Parental leave",
      "description": "Take the time you need to recharge! We want everyone feeling their best at work."
    },
    {
      "title": "Hardware",
      "description": "We’ll equip you with an M4 MacBook, 4K display, and anything else you need."
    },
    {
      "title": "Education",
      "description": "Get reimbursed for relevant books, conferences, classes, and more."
    }
  ],
  "media": [
    {
      "name": "Introducing Assembly",
      "link": "https://assembly.com/blog/copilot-rebrand-assembly",
      "author": "Marlon Misra",
      "date": "September, 2025"
    },
    {
      "name": "Series A Announcement",
      "link": "https://assembly.com/blog/introducing-assembly-1-0-and-announcing-our-series-a/",
      "author": "Marlon Misra",
      "date": "January, 2023"
    },
    {
      "name": "TechCrunch announcement",
      "link": "https://techcrunch.com/2023/01/19/copilot-lands-10m-to-help-service-businesses-build-digital-customer-experiences/",
      "author": "TechCrunch",
      "date": "January, 2023"
    }
  ],
  "faqs": [
    {
      "question": "Where is Assembly located?",
      "answer": "Assembly is located at 900 Broadway in New York City, right by Union Square. It’s a very central location with easy access to multiple subway lines, making it convenient to get to from most parts of the city."
    },
    {
      "question": "What is the interview process like?",
      "answer": "The interview process is designed to be clear and efficient. It starts with a 30-minute screening call to get to know you and understand your background and interests. From there, you’ll have one to two remote interviews, along with a short homework project that takes a few hours and reflects the kind of work you’d do in the role. The final step is an onsite interview at our NYC office, where you’ll meet the team and spend more time on collaboration and fit."
    },
    {
      "question": "Do you sponsor visas?",
      "answer": "We can sponsor visas in some cases, but it depends on the situation. We’re generally able to support straightforward work visas like TNs and other common employment-based visas. More complex or uncertain visa situations may not be a fit."
    },
    {
      "question": "Is the team in person or remote?",
      "answer": "We’re primarily in person at our NYC office, with the option to work from home on Wednesdays. We’re flexible when you need to travel or work remotely, but most of the time, you’ll find us working together in the office. And often sticking around for a game of chess afterward."
    },
    {
      "question": "What benefits does Assembly provide?",
      "answer": "You get significant equity, so you participate in the upside you help create. We have flexible PTO and generally encourage people to take around 20 days per year, but we care more about doing good work than counting days. We do full-team international offsites twice a year and try to pick places that are genuinely interesting — recently that’s included Istanbul, Bali, Lisbon, Mexico City, and Puerto Rico. If you’re sick, take the time you need. From day one, we’ll set you up with an M4 MacBook, a 4K display, and any other equipment you need to do your best work. We also provide free lunch, unlimited snacks during the day, and regularly do team breakfasts and lunches."
    },
    {
      "question": "What about healthcare?",
      "answer": "We offer a Tier 1 Blue Cross health insurance plan. Assembly covers 100% of the premium for employees and 50% of the premium for dependents."
    },
    {
      "question": "What do \"Portal\" and \"Copilot\" refer to?",
      "answer": "You may see Assembly referred to as “Portal” or “Copilot” in older job posts, media, or online content. We’ve rebranded twice over the years as the company and product evolved, and some legacy references are still out there."
    },
    {
      "question": "What stage is the company at?",
      "answer": "Assembly is post–Series A and post–product-market fit. We’re extremely well capitalized and currently have more cash on the balance sheet than we’ve raised to date. Our platform is used by over 1,000 paying customers, and the business is growing quickly."
    },
    {
      "question": "What kind of people do well at Assembly?",
      "answer": "People who do well at Assembly enjoy working in person and value being part of a highly collaborative, in-office environment. They’re kind, direct, and intense in a good way—high standards without being political or abrasive. They’re comfortable with ambiguity, take real ownership of their work, and don’t need everything perfectly defined before moving forward."
    }
  ],
  "seo": {
    "title": "Assembly Jobs | Join our Team",
    "description": "At Assembly, you will directly help entrepreneurs start, run, and grow businesses all around the world. Join us on our mission in our NYC HQ or remotely."
  }
};
