// 1 frozen pages: the /comparison index, as Contentful held them the day
// they were taken out of it. This file IS the source — there is no CMS read
// behind it any more, so a copy change is an edit here and a deploy.
//
// Generated by scripts/freeze-cms.mts. Regenerating overwrites hand edits, so
// once you start editing the copy here, stop regenerating: the CMS entries are
// no longer maintained. Imagery lives in public/images/cms, downloaded with it.
import type { ComparisonIndex } from "./comparisons";
import {
  SIGNUP_URL,
  DEMO_URL,
} from "./constants";

export const FROZEN_COMPARISON_INDEX: ComparisonIndex = {
  "title": "Compare Assembly to alternatives",
  "description": "Learn how Assembly stacks up against competing tools when it comes to pricing, features, support, security, and more.",
  "image": {
    "url": "/images/cms/4xvDPvLoyWEpLr2tgXlp2G-comparison111.webp",
    "alt": "comparison111",
    "width": 1152,
    "height": 984
  },
  "seo": {
    "title": "Compare Assembly to Assembly Alternatives",
    "description": "Learn how Assembly stacks up against the best Assembly alternatives when it comes to pricing, features, support, security, and more."
  },
  "noIndex": false,
  "closing": {
    "title": "The alternative for modern firms",
    "description": "Try for free, no credit card required",
    "ctas": [
      {
        "label": "Get started",
        "href": SIGNUP_URL
      },
      {
        "label": "Book a demo",
        "href": DEMO_URL
      }
    ]
  }
};
