// 5 frozen pages: the job listings, as Contentful held them the day
// they were taken out of it. This file IS the source — there is no CMS read
// behind it any more, so a copy change is an edit here and a deploy.
//
// Generated by scripts/freeze-cms.mts. Regenerating overwrites hand edits, so
// once you start editing the copy here, stop regenerating: the CMS entries are
// no longer maintained. Imagery lives in public/images/cms, downloaded with it.
import type { JobListing } from "./careers";

export const FROZEN_JOB_LISTINGS = [
  {
    "slug": "junior-technical-support-specialist",
    "name": "Junior Technical Support Specialist",
    "department": "Support",
    "description": {
      "data": {},
      "content": [
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "About the role",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "This is an entry-level role that has a flexible location. You’ll join our small but mighty Support + Success team, the friendly tech superheroes who make sure our customers are happy, successful, and never stuck. You’ll tackle customer issues — think accounts, billing, subscriptions, and minor technical hiccups — while learning the ins and outs of our platform. You will become a product expert and be able to address questions that cover existing capabilities and future roadmap features. Over time, you’ll get better at solving more complex problems and become a go-to expert for our users.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Who you are",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You are a recent college graduate or graduated from a technical bootcamp.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You thrive in a technical environment and love helping people solve problems.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Quick on your feet and a fast learner—you enjoy figuring things out as you go.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Tech-savvy and comfortable jumping between tools and systems. Extra points if you’ve played with AWS, Dynamo, Retool, or Front.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Clear and empathetic communicator—you can explain tricky stuff without jargon.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Interested or experienced in working with APIs, databases, and no-code integrations like Retool; Stripe experience is a nice bonus.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You care about users and genuinely want to make their day a little easier.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "What you'll do",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Spend most of your time helping customers — solving issues, answering questions, and keeping them smiling.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Partner with your Support + Success Lead and other teams to tackle tricky problems and find solutions.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Assist with creating and troubleshooting automations through Make and Zapier as well as native Assembly automation workflows.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Translate technical issues into plain language for our customers—no jargon allowed.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Gather info, report bugs, and work with Engineering to improve the product.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Resolve support issues within our SLA agreements, including internal and client accounts, billing and subscriptions, and minor technical issues.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Build a deep understanding of our technical architecture and grow your ability to diagnose and resolve more complex problems.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Why you’ll love it here",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You’ll have real impact on how our customers succeed.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Work with a tight-knit, friendly team who loves collaboration and creativity.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Plenty of room to grow and level up your skills as our company scales.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        }
      ],
      "nodeType": "document"
    },
    "team": [
      {
        "name": "Brittany Nickell",
        "profileLink": "https://www.linkedin.com/in/brittanyleighnickell/",
        "image": {
          "url": "/images/cms/6Wtzv2ER7HK1wujQne8v1c-britt.webp",
          "alt": "Brittany Nickell"
        }
      },
      {
        "name": "Veronique Cadet",
        "profileLink": "https://www.linkedin.com/in/v%C3%A9roniquecadet/",
        "image": {
          "url": "/images/cms/3aoCGbZrlalK0pR7WTr8Yo-ver.webp",
          "alt": "Veronique Cadet"
        }
      }
    ]
  },
  {
    "slug": "account-executive",
    "name": "Account Executive",
    "department": "Sales",
    "description": {
      "data": {},
      "content": [
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "About the role",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "As an Account Executive you will report to the CEO and join our two-person sales team. In this role you’ll run a high-velocity sales motion end-to-end — qualifying leads, running demos, and closing deals. You’ll sell to a wide range of service-based businesses (startups, accounting firms, law firms, agencies, and more), so strong discovery and solutioning matters a lot.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "We’re post-PMF with 1,000+ paying customers, and our sales lead exceeded quota last quarter. We’ll compensate you well, invest deeply in your development, and give you the opportunity to help define our sales process, systems, and tooling as we scale.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "What you'll do",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll run demos and close deals.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll do 5+ demos per day, handle objections, and consistently move deals from first call to close.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll lead discovery and solutioning.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll understand customer workflows and pain points, map them to our product, and propose clear solutions across industries and use cases.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll own your pipeline.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll stay on top of follow-ups, next steps, multi-threading, and deal hygiene. You’ll keep forecasts accurate and momentum high.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll sell value at meaningful price points.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll be comfortable closing deals in the ~$2,500–$50k/year range and communicating ROI clearly.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll become an expert in our product.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll develop deep product fluency — features, positioning, edge cases—and continually sharpen your demo and narrative as the product evolves.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll collaborate tightly with product and the broader team.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll bring crisp feedback from the field — what’s confusing, what’s missing, what’s resonating — and contribute beyond sales (product feedback, marketing, success, etc.).",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll help build the machine.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " Early sales is messy. You’ll help define the playbook: messaging, qualification, demo flow, CRM workflows, enablement, tooling, and reporting.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Who you are",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're experienced.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ve sold in early-to-mid stage startups where you had to be scrappy, self-directed, and willing to get your hands dirty.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're a closer.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You have a track record of hitting quota and running deals through the finish line in a high-velocity environment.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're great at solutioning.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You ask sharp questions, listen closely, and can translate messy customer problems into a clear plan and a confident recommendation.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're experienced selling to our ICP.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ve sold B2B software to service-based businesses — e.g., marketing agencies, accounting firms, law firms, consultancies, and other tech-enabled professional services teams. You understand how owners/operators buy, what they care about, and how to build urgency without being pushy.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're comfortable with technical concepts.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You don’t have to be an engineer, but you should be comfortable discussing concepts like automation workflows, embeddings, no-code tooling, and modern software systems without getting lost.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You communicate clearly.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " Your demos are organized and compelling. Your follow-ups are crisp. You don’t ramble, and you don’t hide the ball.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're competitive and candid.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You like direct feedback, you want to win, and you thrive in a performance culture that’s high-trust and high-expectations.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're hardworking.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You understand that building a category-defining company requires people that work smart and that also work hard.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You love working in person.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " We're convinced that building a strong culture happens face-to-face, and we're looking for people who thrive in highly collaborative, in-person environments.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Sales stack",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Salesforce",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Sybill",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Retool",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Chili Piper",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        }
      ],
      "nodeType": "document"
    },
    "team": [
      {
        "name": "Marlon Misra",
        "profileLink": "https://www.linkedin.com/in/marlonmisra/",
        "image": {
          "url": "/images/cms/467AAyP0ueqdADoYTy63hR-pp.webp",
          "alt": "Marlon Misra"
        }
      },
      {
        "name": "Brittany Nickell",
        "profileLink": "https://www.linkedin.com/in/brittanyleighnickell/",
        "image": {
          "url": "/images/cms/6Wtzv2ER7HK1wujQne8v1c-britt.webp",
          "alt": "Brittany Nickell"
        }
      },
      {
        "name": "Sean Walsh",
        "profileLink": "https://www.linkedin.com/in/seanwalshnyc/",
        "image": {
          "url": "/images/cms/mn6yQCTnVVBh9YVmqbWf5-screenshot_2024-08-07_at_2.11.11_pm.webp",
          "alt": "Team - Sean"
        }
      }
    ]
  },
  {
    "slug": "senior-software-engineer-core-product",
    "name": "Senior Software Engineer",
    "department": "Engineering",
    "description": {
      "nodeType": "document",
      "data": {},
      "content": [
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "About the role",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "paragraph",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "As a senior software engineer you will report to the CTO and be a core member of our engineering and product team. In this role you’ll lead complex technical projects, mentor junior team members, improve velocity through better process, shape the engineering roadmap, and help define our engineering culture. We will compensate you well, invest deeply in your development, and do everything we can to make sure this is the single best work experience of your life.",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "What you'll do",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "unordered-list",
          "data": {},
          "content": [
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll design and build full stack features. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "You'll be working on scaling and enhancing our web platform, our flagship product. This involves overseeing the libraries we use, managing the component/design system architecture, and building the most robust testable features.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll be an owner. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "You'll work with EPD (engineering/product/design) leads team to help shape the roadmap. You’ll also be responsible for writing technical documentation, setting up infrastructure, and organizing engineering tasks.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll balance the short and long term. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "While knowing the importance of shipping quickly you also know how to craft thoughtful long-term technical strategy. You know when to address tech debt and when to improve infrastructure and processes (testing, code reviews, CI/CD).",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You’ll make the engineering team more effective. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "You’ll help us implement better processes, refine our interview process, and help define our engineering culture.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll follow security best practices.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You will be responsible for safeguarding customer data, following secure coding guidelines, and adhering to Assembly’s security, confidentiality, and data protection policies as part of your work. You’ll help ensure that systems, code, and infrastructure are developed and maintained in alignment with our security standards.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll help build the team. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "The first 10 members of an engineering team dictate the next 100. You'll help interview and recruit more talented engineers.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll learn about startups",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": ". Aside from your core work, you'll have the opportunity to get involved in other areas - marketing, growth, ops, etc.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "Who you are",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "unordered-list",
          "data": {},
          "content": [
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You're experienced.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You have 4+ years experience working on complex web applications built with modern tools and a proven track record as a lead developer. Familiarity with our tech stack is a bonus!",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You're passionate about crafting software.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " Whether it's the thrilling moment when a scalable system design sparks excitement, or the deep satisfaction of engineering a seamless, robust frontend component, every line of code is a canvas for your creativity. You take pride in building systems that are as elegant as they are efficient, turning complex challenges into works of art that you love to share and showcase.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You design thoughtful solutions.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You approach challenges by exploring multiple avenues, carefully weighing edge cases and dependencies to deliver the optimal user experience. You excel at articulating your ideas, ensuring that you remain focused on what truly matters: understanding customer needs.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You love to collaborate, discuss and debate.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You engage in respectful, constructive debates—challenging ideas without being confrontational. You work collaboratively to weigh trade-offs and find balanced solutions, clearly explaining your reasoning when opinions differ and valuing the insights of your teammates.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You're hardworking.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You understand that building a category-defining company requires people that work smart and that also work hard.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You love working in person.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " We're convinced that building a strong culture happens face-to-face, and we're looking for people who thrive in highly collaborative, in-person environments.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "Tech",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "unordered-list",
          "data": {},
          "content": [
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "React, Typescript, Golang",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "Libraries: Tailwind, MUI, Redux (rtk-query), AmplifyJS",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "Infra (AWS): DynamoDB, Lambda, Cognito, Cloudwatch, Cloudformation, SQS",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "nodeType": "paragraph",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "",
              "marks": [],
              "data": {}
            }
          ]
        }
      ]
    },
    "team": [
      {
        "name": "Neil Raina",
        "profileLink": "https://www.linkedin.com/in/rnraina/",
        "image": {
          "url": "/images/cms/7qCB26EwQiIfi3DiZlGW8U-nr.webp",
          "alt": "Neil Raina"
        }
      },
      {
        "name": "Kevin Foley",
        "profileLink": "https://www.linkedin.com/in/kevin-foley-006337233/",
        "image": {
          "url": "/images/cms/6v2Pbh7pK2qCULeEO7D3uq-kf.webp",
          "alt": "Kevin"
        }
      },
      {
        "name": "Sal Becker",
        "profileLink": "https://www.linkedin.com/in/salbecker/",
        "image": {
          "url": "/images/cms/1GvOERkr84S7vTi0Pjccih-t6fa6ee67-u0745qm67pd-ab46234e1459-512.webp",
          "alt": "Sal Becker Profile"
        }
      }
    ]
  },
  {
    "slug": "growth-gtm-engineer",
    "name": "Growth & GTM Engineer",
    "department": "Product",
    "description": {
      "data": {},
      "content": [
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "About the role",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "As our first Growth & GTM Engineer, you’ll collaborate closely with the founders and operate at the intersection of engineering, product, and marketing — building both in-product features (onboarding flows, referrals, templates, etc.) and external GTM initiatives (agents that scrape lead lists, outbound automation, and experimenting with next-gen AI tools). This is a highly cross-functional role reporting to the CEO that’s ideal for someone technical who loves rolling up their sleeves, coding prototypes, and iterating on growth strategies that span the entire funnel.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "What you’ll do",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Own product growth features.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll code and optimize onboarding flows, referrals, viral loops, templates, and more.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Automate GTM processes.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll scrape lead lists, set up outbound sequences, and integrate cutting-edge AI tools (like 11x or ",
                      "nodeType": "text"
                    },
                    {
                      "data": {
                        "uri": "http://clay.io"
                      },
                      "content": [
                        {
                          "data": {},
                          "marks": [],
                          "value": "clay.io",
                          "nodeType": "text"
                        }
                      ],
                      "nodeType": "hyperlink"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": ") to supercharge our sales and marketing motions.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Experiment rapidly.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll design and run A/B tests, measure impact, and iterate quickly on ideas that drive user adoption and revenue.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Collaborate across teams.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll partner with product, marketing, sales, and engineering to build cohesive growth roadmaps that align with company objectives.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Drive data-backed decisions.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll track relevant metrics and funnel data, using insights to shape new strategies and refine existing ones.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Stay on the bleeding edge.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll continuously research new tools, platforms, and frameworks for growth, testing what’s possible and bringing the best solutions in-house.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Who you are",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You’re a hybrid.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You have enough technical chops to build and deploy high quality code, and you’re equally comfortable talking growth metrics and marketing ROI.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You love problem-solving.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You enjoy figuring out the fastest way to validate an idea — whether that’s writing a script, spinning up a landing page, or scraping data.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You’re data-driven.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You make decisions based on metrics, using insights to refine experiments and maximize impact.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You’re collaborative.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You thrive on cross-functional projects, naturally bridging the gap between engineering, product, marketing, and sales.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You move fast.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’re scrappy, decisive, and ready to pivot based on real-time feedback.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You’re an early-stage enthusiast.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You understand the excitement (and chaos) of startups, and you’re eager to build from the ground up.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You love working in person.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " We're convinced that building a strong culture happens face-to-face, and we're looking for people who thrive in highly collaborative, in-person environments.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        }
      ],
      "nodeType": "document"
    },
    "team": [
      {
        "name": "Marlon Misra",
        "profileLink": "https://www.linkedin.com/in/marlonmisra/",
        "image": {
          "url": "/images/cms/467AAyP0ueqdADoYTy63hR-pp.webp",
          "alt": "Marlon Misra"
        }
      }
    ]
  },
  {
    "slug": "associate-account-executive",
    "name": "Associate Account Executive",
    "department": "Sales",
    "description": {
      "data": {},
      "content": [
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "About the role",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Assembly is looking for an Associate Account Executive to join our two-person sales team, reporting directly to Sean, our sales lead. This is a full-cycle role — you'll run discovery, demos, and close deals — and it's designed for someone earlier in their career who is hungry to do the real work of selling, not just set meetings for someone else.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "You don't need years of quota-carrying experience. What you do need is sharp communication, genuine curiosity, and the drive to get good fast. You'll work side-by-side with our sales lead every day, which means real mentorship and direct feedback as you grow into owning the full sales cycle.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "We're post-PMF with 1,000+ paying customers, a sales lead who exceeded quota last quarter, and a product our customers love. You'll be stepping into a role with real deal flow and real support.",
              "nodeType": "text"
            },
            {
              "data": {},
              "marks": [],
              "value": " ",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "What you'll do",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Run demos and close deals.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You'll conduct 5+ demos per day, handle objections, and move deals from first call to close.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Lead discovery and solutioning.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You'll ask sharp questions, understand customer workflows, and map them to our product across a wide range of service-based businesses — accounting firms, marketing agencies, law firms, startups, and more.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Own your pipeline.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You'll stay on top of follow-ups, next steps, and deal hygiene. You'll keep your forecast accurate and momentum high.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Sell value confidently.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You'll be comfortable discussing deals in the ~$2,500–$50k/year range and communicating ROI clearly.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Become a product expert.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You'll develop deep fluency in our product — features, positioning, edge cases — and sharpen your demo and narrative as the product evolves.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "Contribute beyond sales.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You'll bring field feedback to product and the broader team, and help shape messaging, qualification criteria, and CRM workflows as we scale.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "Who you are",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're early in your career and ready to do the work.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " Maybe you're a recent grad, maybe you've had a BDR or SDR role, maybe you've done something adjacent to sales. You haven't necessarily closed deals yet, but you're ready to.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're a strong communicator.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " Your writing is crisp, you don't ramble, and you can hold a room's attention. You can explain something complex in plain language.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're curious, coachable, and take real ownership.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You ask good questions, act on feedback, and when something needs doing, you do it — you don't need a perfect playbook to move fast.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're competitive and goal-oriented.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You set high expectations for yourself and care about your own growth. You like having a clear target and the satisfaction of hitting it.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're comfortable with technical concepts.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You don't need to be an engineer, but you should be comfortable discussing things like automation workflows, no-code tooling, and modern software without getting lost.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're hardworking.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " This is a high-volume, high-velocity sales environment. No task is beneath you, and you thrive when the path isn’t perfectly defined.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You love working in person.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " We're a tight-knit team that works better together in the same room. This isn't a remote role and we're looking for someone who genuinely thrives in that kind of environment.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "What you'll get",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Direct mentorship from a quota-exceeding sales lead, in-person every day",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Full-cycle ownership from day one — this isn't a stepping stone to being an AE, it is the AE role",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Competitive base + commission structure",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Real equity and participation in Assembly's upside",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Full-team international offsites (recent destinations: Istanbul, Bali, Lisbon, Mexico City, Puerto Rico)",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "100% covered Tier 1 Blue Cross health insurance",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "M4 MacBook, 4K display, and all the equipment you need",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Free lunch, unlimited snacks, and a team that actually likes each other",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "Sales stack",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Claude",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Front",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "ChatGPT",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Salesforce",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Sybill",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Retool",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Chili Piper",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        }
      ],
      "nodeType": "document"
    },
    "team": [
      {
        "name": "Sean Walsh",
        "profileLink": "https://www.linkedin.com/in/seanwalshnyc/",
        "image": {
          "url": "/images/cms/mn6yQCTnVVBh9YVmqbWf5-screenshot_2024-08-07_at_2.11.11_pm.webp",
          "alt": "Team - Sean"
        }
      },
      {
        "name": "Marlon Misra",
        "profileLink": "https://www.linkedin.com/in/marlonmisra/",
        "image": {
          "url": "/images/cms/467AAyP0ueqdADoYTy63hR-pp.webp",
          "alt": "Marlon Misra"
        }
      }
    ]
  }
] as unknown as JobListing[];
