import type { LegalDocument } from "@/components/legal/legal-document";

// Migrated from assembly.com/legal/privacy-policy. This is legal copy: edit
// the wording only when Legal changes it, and bump `lastUpdated` when they do.
// `**…**` marks the emphasis the source page carries, and links to Assembly’s
// other legal pages point at this site’s own copies of them.
//
// The defined terms in section 2 are set in Title Case ("**Service**"), not the
// source page’s all-caps ("**SERVICE**"). Wording is untouched and they are still
// capitalised defined terms — which is also how the rest of this document already
// refers to them ("our Service", "a Data Controller of your data").
export const PRIVACY_POLICY: LegalDocument = {
  title: "Privacy Policy",
  effective: "April 15, 2022",
  lastUpdated: "08/07/2026",
  parts: [
    {
      id: "1-introduction",
      title: "1. Introduction",
      group: "Overview",
      sections: [
        {
          id: "1-introduction-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Welcome to Copilot Platforms Inc. doing business as “Assembly.”" },
            { type: "p", text: "Copilot Platforms Inc. (“us”, “we”, or “our”) operates https://assembly.com/ (hereinafter referred to as “Service”). Our Privacy Policy governs your visit to https://assembly.com/, and explains how we collect, safeguard, and disclose information that results from your use of our Service." },
            { type: "p", text: "We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions." },
            { type: "p", text: "Our Terms and Conditions (“**Terms**”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“**agreement**”)." },
          ],
        },
      ],
    },
    {
      id: "2-definitions",
      title: "2. Definitions",
      group: "Overview",
      sections: [
        {
          id: "2-definitions-intro",
          heading: null,
          blocks: [
            { type: "p", text: "**Service** means the https://assembly.com/ website operated by Copilot Platforms Inc." },
            { type: "p", text: "**Personal Data** means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession)." },
            { type: "p", text: "**Usage Data** is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit)." },
            { type: "p", text: "**Cookies** are small files stored on your device (computer or mobile device)." },
            { type: "p", text: "**Data Controller** means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data." },
            { type: "p", text: "**Data Subject** is any living individual who is the subject of Personal Data." },
            { type: "p", text: "**The User** is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data." },
          ],
        },
      ],
    },
    {
      id: "3-information-collection-and-use",
      title: "3. Information Collection and Use",
      group: "What we collect",
      shortTitle: "3. Collection and Use",
      sections: [
        {
          id: "3-information-collection-and-use-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We collect several different types of information for various purposes to provide and improve our Service to you." },
          ],
        },
      ],
    },
    {
      id: "4-types-of-data-collected",
      title: "4. Types of Data Collected",
      group: "What we collect",
      sections: [
        {
          id: "4-types-of-data-collected-personal-data",
          heading: "Personal Data",
          blocks: [
            { type: "p", text: "While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“**Personal Data**”). Personally identifiable information may include, but is not limited to:" },
            {
              type: "list",
              items: [
                "Email address",
                "First name and last name",
                "Phone number",
                "Cookies and Usage Data",
              ],
            },
            { type: "p", text: "We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link." },
          ],
        },
        {
          id: "4-types-of-data-collected-usage-data",
          heading: "Usage Data",
          blocks: [
            { type: "p", text: "We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“**Usage Data**”). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data." },
          ],
        },
        {
          id: "4-types-of-data-collected-tracking-cookies-data",
          heading: "Tracking Cookies Data",
          blocks: [
            { type: "p", text: "We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use:" },
            {
              type: "list",
              items: [
                "**Session Cookies**: We use Session Cookies to operate our Service.",
                "**Preference Cookies**: We use Preference Cookies to remember your preferences and various settings.",
                "**Security Cookies**: We use Security Cookies for security purposes.",
                "**Advertising Cookies**: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.",
              ],
            },
          ],
        },
      ],
    },
    {
      id: "5-use-of-data",
      title: "5. Use of Data",
      group: "How we use it",
      sections: [
        {
          id: "5-use-of-data-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Copilot Platforms Inc. uses the collected data for various purposes:" },
            {
              type: "list",
              items: [
                "to provide and maintain our Service;",
                "to notify you about changes to our Service;",
                "to allow you to participate in interactive features of our Service when you choose to do so;",
                "to provide customer support;",
                "to gather analysis or valuable information so that we can improve our Service;",
                "to monitor the usage of our Service;",
                "to detect, prevent and address technical issues;",
                "to fulfill any other purpose for which you provide it;",
                "to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;",
                "to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;",
                "to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;",
                "in any other way we may describe when you provide the information; for any other purpose with your consent.",
              ],
            },
          ],
        },
      ],
    },
    {
      id: "6-retention-of-data",
      title: "6. Retention of Data",
      group: "How we use it",
      sections: [
        {
          id: "6-retention-of-data-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods." },
          ],
        },
      ],
    },
    {
      id: "7-transfer-of-data",
      title: "7. Transfer of Data",
      group: "How we use it",
      sections: [
        {
          id: "7-transfer-of-data-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Copilot Platforms Inc.will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information." },
          ],
        },
      ],
    },
    {
      id: "8-disclosure-of-data-for-law-enforcement",
      title: "8. Disclosure of Data for Law Enforcement",
      group: "How we use it",
      shortTitle: "8. Law Enforcement",
      sections: [
        {
          id: "8-disclosure-of-data-for-law-enforcement-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities." },
          ],
        },
        {
          id: "8-disclosure-of-data-for-law-enforcement-business-transaction",
          heading: "Business Transaction",
          blocks: [
            { type: "p", text: "If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred." },
          ],
        },
        {
          id: "8-disclosure-of-data-for-law-enforcement-other-cases-we-may-disclose-your-information-also",
          heading: "Other cases. We may disclose your information also:",
          blocks: [
            {
              type: "list",
              items: [
                "to our subsidiaries and affiliates;",
                "for the purpose of including your company’s logo on our website;",
                "with your consent in any other cases;",
                "if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.",
              ],
            },
          ],
        },
        {
          id: "8-disclosure-of-data-for-law-enforcement-security-of-data",
          heading: "Security of Data",
          blocks: [
            { type: "p", text: "The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security." },
          ],
        },
      ],
    },
    {
      id: "9-your-data-protection-rights-under-general-data-protection-regulation-gdpr",
      title: "9. Your Data Protection Rights Under General Data Protection Regulation (GDPR)",
      group: "Your rights",
      shortTitle: "9. GDPR Rights",
      sections: [
        {
          id: "9-your-data-protection-rights-under-general-data-protection-regulation-gdpr-intro",
          heading: null,
          blocks: [
            { type: "p", text: "If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data." },
            { type: "p", text: "If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@assembly.com." },
            { type: "p", text: "In certain circumstances, you have the following data protection rights:" },
            {
              type: "list",
              items: [
                "the right to access, update or to delete the information we have on you;",
                "the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;",
                "the right to object. You have the right to object to our processing of your Personal Data;",
                "the right of restriction. You have the right to request that we restrict the processing of your personal information;",
                "the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;",
                "the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;",
              ],
            },
            { type: "p", text: "Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data." },
            { type: "p", text: "You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA)." },
          ],
        },
      ],
    },
    {
      id: "10-your-data-protection-rights-under-the-california-privacy-protection-act-caloppa",
      title: "10. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)",
      group: "Your rights",
      shortTitle: "10. CalOPPA Rights",
      sections: [
        {
          id: "10-your-data-protection-rights-under-the-california-privacy-protection-act-caloppa-intro",
          heading: null,
          blocks: [
            { type: "p", text: "CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/" },
            { type: "p", text: "According to CalOPPA we agree to the following:" },
            {
              type: "list",
              items: [
                "users can visit our site anonymously;",
                "our Privacy Policy link includes the word “**Privacy**”, and can easily be found on the page specified above on the home page of our website;",
                "users will be notified of any privacy policy changes on our Privacy Policy Page;",
                "users are able to change their personal information by emailing us at support@assembly.com.",
              ],
            },
            { type: "p", text: "Our Policy on “**Do Not Track**” Signals:" },
            { type: "p", text: "We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked." },
            { type: "p", text: "You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser." },
          ],
        },
      ],
    },
    {
      id: "11-your-data-protection-rights-under-the-california-consumer-privacy-act-ccpa",
      title: "11. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)",
      group: "Your rights",
      shortTitle: "11. CCPA Rights",
      sections: [
        {
          id: "11-your-data-protection-rights-under-the-california-consumer-privacy-act-ccpa-intro",
          heading: null,
          blocks: [
            { type: "p", text: "If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:" },
            {
              type: "list",
              items: [
                "**What personal information we have about you**. If you make this request, we will return to you:",
                "The categories of personal information we have collected about you.",
                "The categories of sources from which we collect your personal information.",
                "The business or commercial purpose for collecting or selling your personal information.",
                "The categories of third parties with whom we share personal information.",
                "The specific pieces of personal information we have collected about you.",
                "A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.",
                "A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.",
              ],
            },
            { type: "p", text: "Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months." },
            {
              type: "list",
              items: [
                "**To delete your personal information**. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.",
                "**To stop selling your personal information**. We don't sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.",
              ],
            },
            { type: "p", text: "Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights." },
            { type: "p", text: "To exercise your California data protection rights described above, please send your request(s) by one of the following means:" },
            { type: "p", text: "By email: support@assembly.com" },
            { type: "p", text: "Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020." },
          ],
        },
      ],
    },
    {
      id: "12-service-providers",
      title: "12. Service Providers",
      group: "Third parties and AI",
      sections: [
        {
          id: "12-service-providers-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We may employ third party companies and individuals to facilitate our Service (“**Service Providers**”), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. An up-to-date list of our service providers can be found on our [Subprocessor](https://security.assembly.com/subprocessors) list." },
          ],
        },
      ],
    },
    {
      id: "13-analytics",
      title: "13. Analytics",
      group: "Third parties and AI",
      sections: [
        {
          id: "13-analytics-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We may use third-party Service Providers to monitor and analyze the use of our Service." },
          ],
        },
        {
          id: "13-analytics-google-analytics",
          heading: "Google Analytics",
          blocks: [
            { type: "p", text: "Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245." },
          ],
        },
        {
          id: "13-analytics-segment",
          heading: "Segment",
          blocks: [
            { type: "p", text: "Segment.io is a web traffic analysis tool. You can read the Privacy Policy for Segment.io here: https://segment.com/legal/privacy/." },
          ],
        },
      ],
    },
    {
      id: "14-ci-cd-tools",
      title: "14. CI/CD tools",
      group: "Third parties and AI",
      sections: [
        {
          id: "14-ci-cd-tools-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We may use third-party Service Providers to automate the development process of our Service." },
          ],
        },
        {
          id: "14-ci-cd-tools-github",
          heading: "GitHub",
          blocks: [
            { type: "p", text: "GitHub is provided by GitHub, Inc. GitHub is a development platform to host and review code, manage projects, and build software. For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: https://help.github.com/en/articles/github-privacy-statement." },
          ],
        },
      ],
    },
    {
      id: "15-behavioral-remarketing",
      title: "15. Behavioral Remarketing",
      group: "Third parties and AI",
      shortTitle: "15. Remarketing",
      sections: [
        {
          id: "15-behavioral-remarketing-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Assembly Platforms Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service." },
          ],
        },
        {
          id: "15-behavioral-remarketing-google-ads-adwords",
          heading: "Google Ads (AdWords)",
          blocks: [
            { type: "p", text: "Google Ads (AdWords) remarketing service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads Google also recommends installing the Google Analytics Opt-out Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en" },
          ],
        },
        {
          id: "15-behavioral-remarketing-facebook",
          heading: "Facebook",
          blocks: [
            { type: "p", text: "Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950 To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/568137493302217 Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings. For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation" },
          ],
        },
      ],
    },
    {
      id: "16-payments",
      title: "16. Payments",
      group: "Third parties and AI",
      sections: [
        {
          id: "16-payments-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information. The payment processors we work with are:" },
          ],
        },
        {
          id: "16-payments-stripe",
          heading: "Stripe",
          blocks: [
            { type: "p", text: "Their Privacy Policy can be viewed at: https://stripe.com/us/privacy" },
          ],
        },
      ],
    },
    {
      id: "17-ai-features-and-ai-connectors",
      title: "17. AI Features and AI Connectors",
      group: "Third parties and AI",
      shortTitle: "17. AI Features",
      sections: [
        {
          id: "17-ai-features-and-ai-connectors-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Assembly offers different AI capabilities within the Service. For a complete list, see [**Assembly's AI Policy & Data Handling page**](/legal/ai-policy)." },
            { type: "p", text: "For Assembly's in-product AI features, neither Assembly nor the applicable Service Provider uses inputs or outputs to train AI models. For MCP connections, the third-party AI provider is an **independent third party that the customer has chosen** — not Assembly's Service Provider — and the customer is responsible for the AI provider's processing of data after it leaves Assembly's Service, including any logging, retention, training, or onward sharing the AI provider performs under its own terms. Customers should review the AI provider's privacy policy, terms, and any applicable data-processing agreement before connecting." },
            { type: "p", text: "Assembly does not use traffic from its in-product AI features or MCP to train AI models, sell or \"share\" it under the California Privacy Rights Act, or use it for marketing. The retention principles in Section 6 (Retention of Data), the transfer disclosures in Section 7 (Transfer of Data), and the rights described in Sections 10 (GDPR) and 12 (CCPA) apply." },
            { type: "p", text: "For complete and up-to-date information about how Assembly Assistant, additional AI features, and MCP work — including data categories, retention periods, sub-processors, audit logging, customer responsibilities, and how to revoke access — see [**Assembly's AI Policy & Data Handling page**](/legal/ai-policy). Assembly will update that page as functionality changes; material changes affecting this Privacy Policy will be reflected here as described in Section 20." },
          ],
        },
        {
          id: "17-ai-features-and-ai-connectors-google-user-data",
          heading: "Google user data",
          blocks: [
            { type: "p", text: "Assembly's use of information received from Google Workspace APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. Google user data accessed through a connected Google account is used only to provide the user-facing features of the application a customer has built on Assembly, including features of those applications that use AI to produce a result for the user. It is not used, transferred, or sold to create, train, or improve any generalized or foundational machine learning or artificial intelligence model." },
          ],
        },
      ],
    },
    {
      id: "18-links-to-other-sites",
      title: "18. Links to Other Sites",
      group: "Third parties and AI",
      sections: [
        {
          id: "18-links-to-other-sites-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services." },
          ],
        },
      ],
    },
    {
      id: "19-children-s-privacy",
      title: "19. Children's Privacy",
      group: "Children, changes and contact",
      sections: [
        {
          id: "19-children-s-privacy-intro",
          heading: null,
          blocks: [
            { type: "p", text: "Our Services are not intended for use by children under the age of 18 (“**Child**” or “**Children**”). We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers." },
          ],
        },
      ],
    },
    {
      id: "20-changes-to-this-privacy-policy",
      title: "20. Changes to This Privacy Policy",
      group: "Children, changes and contact",
      shortTitle: "20. Policy Changes",
      sections: [
        {
          id: "20-changes-to-this-privacy-policy-intro",
          heading: null,
          blocks: [
            { type: "p", text: "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page." },
          ],
        },
      ],
    },
    {
      id: "21-contact-us",
      title: "21. Contact Us",
      group: "Children, changes and contact",
      sections: [
        {
          id: "21-contact-us-intro",
          heading: null,
          blocks: [
            { type: "p", text: "If you have any questions about this Privacy Policy, please contact us:" },
            { type: "p", text: "By email: support@assembly.com." },
          ],
        },
      ],
    },
  ],
};
