import { Accordion, type FAQEntry } from "@/components/home/faq";
import { GRID_LINE } from "@/components/ui/grid-lines";
import { Reveal } from "@/components/ui/reveal";
import { SecurityCompliance } from "@/components/security/security-compliance";
import { TRUST_CENTER_URL } from "@/lib/constants";

/**
 * The claims a safety-first buyer checks, collapsed to their titles.
 *
 * Set as rows rather than as one block of prose, the way the stack section
 * above does it: these are three separate questions, and the HIPAA answer in
 * particular is a boundary a covered entity has to read in full. As a paragraph
 * it was six lines of qualification sitting under a one-line claim; as a drawer
 * it is there for the reader it is written for and out of the way of everyone
 * else.
 */
const CLAIMS: FAQEntry[] = [
  {
    question: "Logins and permissions",
    answer:
      "Logins, permissions, and data isolation are platform infrastructure, engineered, audited, and on by default.",
  },
  {
    question: "How clients sign in",
    answer:
      "Clients sign in with Google or a secure one-click email link, with multi-factor authentication available on every plan.",
  },
  {
    question: "HIPAA",
    answer:
      "Assembly supports HIPAA with a BAA on the Advanced plan, with one boundary: AI features are not covered. Ready-made apps like secure messaging, file sharing, and contracts can handle PHI as long as the app does not use AI. Apps built with the AI app builder are not HIPAA-covered, because the build process uses AI. If you are a covered entity, talk to us and we will map what fits where.",
  },
];

/** Clears the safety-first buyer's objections. */
export function PortalTrust({
  heading = "Secure by the platform, not by the prompt.",
  body = "Logins, permissions, and data isolation are engineered, audited, and on by default — never generated by the AI for each app.",
  claims = CLAIMS,
  link = { label: "Visit the Trust Center", href: TRUST_CENTER_URL },
  omitSeals,
  visual,
}: {
  heading?: string;
  body?: string;
  claims?: FAQEntry[];
  link?: { label: string; href: string };
  /** Seal titles to leave out of the compliance band. */
  omitSeals?: string[];
  /**
   * Fills the right column when `claims` is empty — for a brief that makes the
   * security case in its paragraph rather than in rows a reader opens.
   */
  visual?: React.ReactNode;
} = {}) {
  const external = link.href.startsWith("http");
  return (
    <section className="mx-auto max-w-[1200px] px-6 pt-16 md:px-10 md:pt-24">
      <Reveal>
        {/* Same two-column shape as the stack section: claim and its way out on
            the left, the rows that answer it on the right. */}
        <div className="grid gap-10 md:grid-cols-2 md:gap-16">
          <div className="md:self-start">
            <h2 className="type-h2 text-balance">{heading}</h2>
            <p className="mt-5 max-w-md text-muted-foreground">{body}</p>
            <a
              href={link.href}
              {...(external
                ? { target: "_blank", rel: "noopener noreferrer" }
                : {})}
              className="mt-6 inline-block rounded-lg border border-border px-4 py-1.5 text-sm text-muted-foreground transition-colors hover:border-foreground/20 hover:text-foreground"
            >
              {link.label}
            </a>
          </div>

          {/* The same accordion treatment as the stack section above, so the
              two sets of rows on this page read as one control. */}
          {claims.length ? (
          <div
            className={[
              "[&>div>div>*]:pl-5 [&>div>div>*]:pr-5",
              "[&>div>div]:transition-colors [&>div>div]:hover:bg-muted/50 [[data-theme=dark]_&]:[&>div>div]:hover:bg-white/[0.04]",
            ].join(" ")}
          >
            <Accordion
              items={claims}
              twoColumn={false}
              variant="divided"
              dottedRules
              flushTop={false}
            />
          </div>
          ) : (
            visual
          )}
        </div>

        {/* The certifications close the argument the rows just made. Pulled
            out past the section's padding so the band's outer cells land on the
            rails, and opened by its own rule. It closes on the section divider
            instead of drawing a second one, so the section carries no bottom
            padding: the band runs to the end of it. */}
        <div className={`-mx-6 mt-14 border-t md:-mx-10 ${GRID_LINE}`}>
          <SecurityCompliance omit={omitSeals} />
        </div>
      </Reveal>
    </section>
  );
}
