import Link from "next/link";
import { Reveal } from "@/components/ui/reveal";
import { VisualSlot } from "@/components/ui/visual-slot";
import { DEMO_URL, TRUST_CENTER_URL } from "@/lib/constants";

/**
 * Clears the safety-first buyer's objections, and states the HIPAA boundary
 * honestly rather than leaving a covered entity to discover it.
 *
 * The HIPAA paragraph is the approved wording and matches the security page's
 * FAQ answer verbatim. It needs legal sign-off before this page ships, and it
 * must never imply that AI-built apps can handle PHI.
 */
export function PortalTrust() {
  return (
    <section className="mx-auto max-w-[1200px] px-6 py-16 md:px-10 md:py-24">
      <Reveal>
        <div className="grid gap-10 md:grid-cols-2 md:gap-16">
          <div className="md:self-start">
            <h2 className="type-h2 text-balance">
              Secure by the platform, not by the prompt.
            </h2>
            <p className="mt-5 max-w-md text-muted-foreground">
              Logins, permissions, and data isolation are platform
              infrastructure, never generated by AI. Clients sign in with a
              secure one-click email link or Google, with multi-factor
              authentication available on every plan.
            </p>
            <p className="mt-5 max-w-md text-sm leading-relaxed text-muted-foreground">
              Assembly supports HIPAA with a BAA on the Advanced plan, with one
              boundary: AI features are not covered. Ready-made apps like secure
              messaging, file sharing, and contracts can handle PHI as long as
              the app does not use AI. Apps built with the AI app builder are
              not HIPAA-covered, because the build process uses AI. If you are a
              covered entity,{" "}
              <Link
                href={DEMO_URL}
                className="underline underline-offset-2 transition-colors hover:text-foreground"
              >
                talk to us
              </Link>{" "}
              and we will map what fits where.
            </p>
            <a
              href={TRUST_CENTER_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-6 inline-block text-sm text-muted-foreground underline underline-offset-4 transition-colors hover:text-foreground"
            >
              Visit the Trust Center
            </a>
          </div>

          <VisualSlot
            ratio="4 / 3"
            label="Trust visual"
            description="An isolation diagram: one workspace boundary containing several app cards, each with its own small database icon, all sitting on a shared platform layer bar labelled logins, permissions, hosting, data scoping. A small inset shows the Brandmages client sign-in with its email-link and Google options. The compliance seals below carry the certifications, so they are not repeated here."
          />
        </div>
      </Reveal>
    </section>
  );
}
