import { GRID_LINE } from "@/components/ui/grid-lines";
import { Reveal } from "@/components/ui/reveal";
import { VisualSlot } from "@/components/ui/visual-slot";

const STEPS = [
  {
    name: "Describe",
    body: "Say what you want, or start from a template.",
  },
  {
    name: "Plan",
    body: "The builder asks a few questions and shows a plan you approve or edit before anything is built.",
  },
  {
    name: "Build",
    body: "A real app deploys into your workspace: team view in your dashboard, client view in your client experience. New apps stay hidden from clients until you make them visible.",
  },
  {
    name: "Iterate",
    body: "Keep chatting to change anything, before launch or six months later.",
  },
];

/**
 * Where the page earns its headline: the mechanism, and the trust moment.
 *
 * It sits after the ready-made apps deliberately. Leading with the builder
 * would read as a developer tool to the operator this page is for; leading with
 * what is already there makes them safe enough to read this.
 */
export function PortalBuild() {
  return (
    <section
      id="build"
      className="mx-auto max-w-[1200px] px-6 py-16 md:px-10 md:py-24"
    >
      <Reveal>
        <h2 className="type-h2 text-balance">
          Build the features unique to your firm.
        </h2>
        <p className="mt-4 max-w-2xl text-muted-foreground">
          Tell us what you want. Assembly shows you a plan to approve or edit,
          then ships your app into your portal with logins, permissions,
          branding, and payments already handled.
        </p>

        <ol className={`mt-10 grid divide-y rounded-xl border md:grid-cols-4 md:divide-x md:divide-y-0 ${GRID_LINE} divide-border [[data-theme=dark]_&]:divide-[#383838]`}>
          {STEPS.map((step, i) => (
            <li key={step.name} className="p-5">
              <span className="type-eyebrow text-muted-foreground">
                Step {i + 1}
              </span>
              <p className="mt-2 text-sm">{step.name}</p>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                {step.body}
              </p>
            </li>
          ))}
        </ol>

        <p className="mt-6 max-w-2xl rounded-lg bg-muted p-4 text-sm leading-relaxed text-muted-foreground">
          Logins, permissions, and payments are platform infrastructure, built
          and maintained by Assembly, never generated by the AI for each app.
        </p>

        <VisualSlot
          className="mt-10"
          label="Build visual"
          description="Two panels, prompt on the left and portal on the right. Left: a chat thread where the operator asks for a project tracker each client sees for their own project, and the builder replies with a readable Plan card listing the fields, who sees it, and the team view, with Approve and Edit. Right: the Brandmages portal with a new Project Tracker item appearing in the sidebar and a Hidden from clients toggle on the new app, switched off."
        />
      </Reveal>
    </section>
  );
}
