import Link from "next/link";
import { Reveal } from "@/components/ui/reveal";
import { SIGNUP_URL } from "@/lib/constants";
import { CardRail, RailCard } from "@/components/ui/card-rail";
import {
  BuildCard,
  DescribeCard,
  IterateCard,
  PlanCard,
  SecuredCard,
} from "@/components/client-portal/portal-build-cards";

/**
 * The handoff's section 5 captions, in its wording.
 *
 * Exported so a page can run a PREFIX of them rather than restating the copy:
 * /client-portal takes the first three, and taking them from here is what
 * stops its wording drifting from the full set.
 */
// Spelled out, not "Step 1".
//
// The kicker is prose — it sits in the page's own face beside a sentence, not
// in a mono label or a numbered badge — and a numeral in a line of words reads
// as a count of items rather than as a position in a sequence. "Step Three" is
// how you would say it out loud, which is the test for a line that is read
// rather than scanned. Five is as far as any caller goes (see BUILD_STEPS);
// the index falls back to the numeral rather than breaking if that changes.
const STEP_WORDS = ["One", "Two", "Three", "Four", "Five"];

export const BUILD_STEPS = [
  {
    name: "Describe",
    // Two lines, like the other four. One line long, this caption left the
    // first card's foot sitting above the rest of the rail's.
    body: "Say what you want, or start from one of 30+ working templates.",
    visual: <DescribeCard />,
  },
  {
    name: "Plan",
    body: "The builder asks a few questions, then shows a plan you approve or edit.",
    visual: <PlanCard />,
  },
  {
    name: "Build",
    body: "A real app lands in your dashboard and portal, hidden until you make it visible.",
    visual: <BuildCard />,
  },
  {
    name: "Iterate",
    body: "Keep chatting to change anything, before launch or six months later.",
    visual: <IterateCard />,
  },
  // The handoff's support line, as a fifth step rather than a line under the
  // rail. It is the answer to the question the four before it raise, so it
  // belongs in the sequence where the reader meets it — not as a footnote they
  // have already scrolled past. Cut to two lines like every other caption:
  // "generated by the AI for each app" ran to three, and the rail's feet stop
  // lining up the moment one caption is deeper than the rest.
  {
    name: "Secured",
    body: "Logins and permissions are built and maintained by Assembly, never by the AI.",
    visual: <SecuredCard />,
  },
];

/**
 * Where the page earns its headline: the mechanism, and the trust moment.
 *
 * It sits after the ready-made apps deliberately. Leading with the builder
 * would read as a developer tool to the operator this page is for; leading with
 * what is already there makes them safe enough to read this.
 *
 * Drawn as a rail rather than one composed shot: the four steps are a sequence,
 * and a sequence reads better as four pictures you move through than as one
 * picture with the steps listed underneath it.
 */
/**
 * Copy, steps and the closing action are props. A vertical page runs its own
 * sequence through the same rail: /solutions/accounting-client-portal carries
 * three steps rather than five, because its trust section states the "built by
 * Assembly, not by the AI" beat that the fifth card makes here.
 */
export function PortalBuild({
  heading = "Build the features unique to your firm.",
  body = "Tell us what you want, approve the plan, and a real app lands in your portal with logins, permissions, and branding already handled.",
  steps = BUILD_STEPS,
  cta = { label: "Describe your first app", href: SIGNUP_URL },
  chips,
  link,
  visual,
  railLabel = "How building works",
}: {
  heading?: string;
  body?: string;
  steps?: typeof BUILD_STEPS;
  cta?: { label: string; href: string };
  /** Examples of what gets built, under the rail. */
  chips?: string[];
  /** The secondary action, beside the primary one. */
  link?: { label: string; href: string };
  /**
   * One picture in place of the rail, for a brief that states the mechanism in
   * a paragraph rather than stepping through it. Passing `steps: []` drops the
   * rail; this takes its place.
   */
  visual?: React.ReactNode;
  railLabel?: string;
} = {}) {
  return (
    <section
      id="build"
      className="mx-auto max-w-[1200px] px-6 py-16 md:px-10 md:py-24"
    >
      <Reveal>
        <div className="text-center">
          <h2 className="type-h2 mx-auto max-w-3xl text-balance">{heading}</h2>
          <p className="mx-auto mt-4 max-w-2xl text-balance text-muted-foreground">
            {body}
          </p>
          <div className="mt-6 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <a
              href={cta.href}
              className="w-full rounded-lg bg-foreground px-5 py-3 text-center text-sm text-background transition-opacity hover:opacity-90 sm:w-auto sm:py-2.5"
            >
              {cta.label}
            </a>
            {link ? (
              <Link
                href={link.href}
                className="w-full rounded-lg border border-foreground/20 bg-transparent px-5 py-3 text-center text-sm text-foreground transition-colors hover:bg-foreground/5 sm:w-auto sm:py-2.5 [[data-theme=dark]_&]:border-white/25"
              >
                {link.label}
              </Link>
            ) : null}
          </div>
        </div>

        {steps.length ? (
          <div className="mt-12">
            {/* One rail whatever the length. The three-step cut has nowhere to
              scroll from lg — the card widths there are exactly a three-column
              track — so it comes out as a complete row with the arrows, the
              drag and the grab cursor all stood down, while on a phone it is
              still a row to swipe rather than three tall cards to scroll past.
              The five-step cut steps at every width. */}
            <CardRail label={railLabel}>
              {steps.map((step, i) => (
                <RailCard
                  key={step.name}
                  index={`Step ${STEP_WORDS[i] ?? i + 1}`}
                  name={step.name}
                  caption={step.body}
                >
                  {step.visual}
                </RailCard>
              ))}
            </CardRail>
          </div>
        ) : null}
        {visual}

        {/* Examples under the rail, as the site's mono chip rather than a new
            pill: these are labels for things the builder makes, the same object
            the filters and tags elsewhere already are. */}
        {chips?.length ? (
          <ul className="mt-8 flex flex-wrap items-center justify-center gap-1.5">
            {chips.map((label) => (
              <li
                key={label}
                className="rounded-md bg-muted px-3 py-1.5 font-mono text-[11px] uppercase leading-none tracking-wide text-muted-foreground [[data-theme=dark]_&]:bg-white/[0.06]"
              >
                {label}
              </li>
            ))}
          </ul>
        ) : null}
      </Reveal>
    </section>
  );
}
