import { Reveal } from "@/components/ui/reveal";
import { VisualSlot } from "@/components/ui/visual-slot";
import { TRUST_CENTER_URL } from "@/lib/constants";

/** Clears the safety-first buyer's objections. */
export function PortalTrust() {
  return (
    <section className="mx-auto max-w-[1200px] px-6 py-16 md:px-10 md:py-24">
      <Reveal>
        <div className="text-center">
          <h2 className="type-h2 mx-auto max-w-3xl text-balance">
            Secure by the platform, not by the prompt
          </h2>
          <p className="mx-auto mt-5 max-w-2xl text-balance text-muted-foreground">
            Logins, permissions, and data isolation are platform infrastructure,
            never generated by AI. Clients sign in with a secure one-click email
            link or Google, with multi-factor authentication available on every
            plan.
          </p>
          <a
            href={TRUST_CENTER_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="mt-6 inline-block rounded-lg border border-border px-4 py-1.5 text-sm text-muted-foreground transition-colors hover:border-foreground/20 hover:text-foreground"
          >
            Visit the Trust Center
          </a>
        </div>

        <VisualSlot
          className="mx-auto mt-12 max-w-4xl"
          ratio="16 / 9"
          label="Trust visual"
          description="An isolation diagram: one workspace boundary containing several app cards, each with its own small database icon, all sitting on a shared platform layer bar labelled logins, permissions, hosting, data scoping. A small inset shows the Brandmages client sign-in with its email-link and Google options. The compliance seals below carry the certifications, so they are not repeated here."
        />
      </Reveal>
    </section>
  );
}
