import { Reveal } from "@/components/ui/reveal";
import { SIGNUP_URL } from "@/lib/constants";
import { CardRail, RailCard } from "@/components/ui/card-rail";
import {
  BuildCard,
  DescribeCard,
  IterateCard,
  PlanCard,
  SecuredCard,
} from "@/components/client-portal/portal-build-cards";

// The handoff's section 5 captions, in its wording.
const STEPS = [
  {
    name: "Describe",
    body: "Say what you want, or start from a template.",
    visual: <DescribeCard />,
  },
  {
    name: "Plan",
    body: "The builder asks a few questions, then shows a plan you approve or edit.",
    visual: <PlanCard />,
  },
  {
    name: "Build",
    body: "A real app lands in your dashboard and portal, hidden until you make it visible.",
    visual: <BuildCard />,
  },
  {
    name: "Iterate",
    body: "Keep chatting to change anything, before launch or six months later.",
    visual: <IterateCard />,
  },
  // The handoff's support line, as a fifth step rather than a line under the
  // rail. It is the answer to the question the four before it raise, so it
  // belongs in the sequence where the reader meets it — not as a footnote they
  // have already scrolled past. Cut to two lines like every other caption:
  // "generated by the AI for each app" ran to three, and the rail's feet stop
  // lining up the moment one caption is deeper than the rest.
  {
    name: "Secured",
    body: "Logins and permissions are built and maintained by Assembly, never by the AI.",
    visual: <SecuredCard />,
  },
];

/**
 * Where the page earns its headline: the mechanism, and the trust moment.
 *
 * It sits after the ready-made apps deliberately. Leading with the builder
 * would read as a developer tool to the operator this page is for; leading with
 * what is already there makes them safe enough to read this.
 *
 * Drawn as a rail rather than one composed shot: the four steps are a sequence,
 * and a sequence reads better as four pictures you move through than as one
 * picture with the steps listed underneath it.
 */
export function PortalBuild() {
  return (
    <section
      id="build"
      className="mx-auto max-w-[1200px] px-6 py-16 md:px-10 md:py-24"
    >
      <Reveal>
        <div className="text-center">
          <h2 className="type-h2 mx-auto max-w-3xl text-balance">
            Build the features unique to your firm.
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-balance text-muted-foreground">
            Tell us what you want, approve the plan, and a real app lands in
            your portal with logins, permissions, and branding already handled.
          </p>
          <a
            href={SIGNUP_URL}
            className="mt-6 inline-block rounded-lg bg-foreground px-5 py-2.5 text-center text-sm text-background transition-opacity hover:opacity-90"
          >
            Describe your first app
          </a>
        </div>

        <div className="mt-12">
          <CardRail label="How building works">
            {STEPS.map((step, i) => (
              <RailCard
                key={step.name}
                index={`Step ${i + 1}`}
                name={step.name}
                caption={step.body}
              >
                {step.visual}
              </RailCard>
            ))}
          </CardRail>
        </div>
      </Reveal>
    </section>
  );
}
