import type { Metadata } from "next";
import { CTA } from "@/components/home/cta";
import { FAQ, type FAQEntry } from "@/components/home/faq";
import { GridDivider, GridRails } from "@/components/ui/grid-lines";
import { PortalSocialProof } from "@/components/client-portal/portal-social-proof";
import { PortalProblem } from "@/components/client-portal/portal-problem";
import { PortalReadyMade } from "@/components/client-portal/portal-ready-made";
import { BUILD_STEPS, PortalBuild } from "@/components/client-portal/portal-build";
import { PortalTailor } from "@/components/client-portal/portal-tailor";
import { PortalStack } from "@/components/client-portal/portal-stack";
import { PortalTrust } from "@/components/client-portal/portal-trust";
import { PortalPricing } from "@/components/client-portal/portal-pricing";
import { PortalProof } from "@/components/client-portal/portal-proof";
import { BuilderHeroVisual } from "@/components/ai-app-builder/builder-hero-visual";
import { DEMO_URL, SIGNUP_URL } from "@/lib/constants";
import { PAGE_SEO, pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata(PAGE_SEO.clientPortal);

/**
 * Every question carries "client portal" for search, and every answer carries
 * the page's thesis: this is the portal you can build on. Earnest objections
 * first, the two search questions last.
 */
const PORTAL_FAQS: FAQEntry[] = [
  {
    question: "What is a client portal?",
    answer:
      "A client portal is a secure, branded hub where your clients message you, pay invoices, sign contracts, share files, and track work in one place. Assembly gives you those as ready-made apps you install in a click, then lets you build custom apps into the same portal.",
  },
  {
    question: "Can I build my own apps into it?",
    answer:
      "Yes. Describe the app you need and Assembly's AI app builder shows you a plan to approve or edit, then ships a real app into your portal with logins, permissions, and branding already handled. Change it later the same way, by chatting.",
    links: [{ label: "Assembly's AI app builder", href: "/ai-app-builder" }],
  },
  {
    question: "Do I need to code to customize it?",
    answer:
      "No. There is nothing to code. You describe what you want, review a plan, and publish. You can also start from 30+ ready-made templates, each a working app, and tell the builder what to change.",
    links: [{ label: "30+ ready-made templates", href: "/templates" }],
  },
  {
    question: "Can I white-label it?",
    answer:
      "Yes. Your logo and colors are on every plan. On Professional and up, clients sign in on your own domain with the Assembly badge removed, so the whole experience feels like your firm's software. Every new app you build inherits the brand automatically.",
  },
  {
    question: "Is my client portal secure?",
    answer:
      "Yes. Logins, permissions, and data isolation are platform infrastructure maintained by Assembly, never generated by AI. Assembly is SOC 2 Type II certified and GDPR and CCPA aligned, clients sign in with a secure email link or Google, and each app runs in its own sandboxed database.",
    links: [{ label: "SOC 2 Type II certified", href: "/security" }],
  },
  {
    question: "Is there a HIPAA-compliant portal?",
    answer:
      "Assembly supports HIPAA with a BAA on the Advanced plan. Ready-made apps like secure messaging, files, and contracts can handle PHI as long as the app does not use AI. Apps built with the AI app builder are not HIPAA-covered, because the build uses AI. Talk to us and we will map what fits.",
    links: [{ label: "Talk to us", href: DEMO_URL }],
  },
  {
    question: "The best client portal for service firms?",
    answer:
      "The best client portal is the one clients actually log in to, and the one your firm does not have to settle for. Assembly combines ready-made messaging, billing, files, contracts, forms, and tasks with an AI app builder, so agencies, accountants, consultants, and coaches get the essentials on day one and the custom apps only their firm needs.",
  },
  {
    question: "What is it not good for?",
    answer:
      "Public marketing websites. Assembly builds authenticated experiences for your team and your logged-in clients. A public site is better built elsewhere and linked from inside your portal.",
  },
];

/**
 * Collective CPA leads here rather than AdvertAI (which leads the builder and
 * comparison pages): the quote is this page's thesis in a customer's own words,
 * and accounting is the slower-converting, safety-first segment this page most
 * needs to reach. Already public on /customers, so nothing waits on approval.
 */
export default function ClientPortalPage() {
  return (
    <>
      {/* Hero — the category the visitor searched for, and the thesis, in one
          breath. "Build on" is the one phrase no legacy portal (no builder) and
          no code-generation tool (no portal) can claim. Same split header as
          the AI app builder page: stacked, the detail follows the headline and
          the actions close the block. */}
      <section className="pb-16 pt-24 md:pb-24 md:pt-32">
        <div className="mx-auto max-w-[1400px] px-6 md:px-10">
          <div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:items-start lg:gap-x-16">
            <h1 className="type-display max-w-[16ch] text-balance">
              The client portal you can build on
            </h1>
            <p className="type-lead max-w-[34rem] text-pretty text-muted-foreground lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:pt-2">
              Ready-made apps for the work every firm shares, plus an AI app
              builder for the work that is only yours.
            </p>
            <div>
              {/* Stacked and full width on phones, side by side from md.
                  Sized to their own text, the pair stacked into two different
                  widths with a ragged right edge, and each sat under the 44px
                  tap target. Full width only on true phones: from sm there is
                  room for the pair side by side at their own size, and holding
                  them full width to md left two very wide buttons on a tablet.
                  Matches the pricing billing toggle's shape (w-full, then
                  w-auto at a breakpoint). */}
              <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center">
                <a
                  href={SIGNUP_URL}
                  className="w-full rounded-lg bg-foreground px-5 py-3 text-center text-sm text-background transition-opacity hover:opacity-90 sm:w-auto sm:py-2.5"
                >
                  Get started free
                </a>
                <a
                  href={DEMO_URL}
                  className="w-full rounded-lg border border-foreground/20 bg-transparent px-5 py-3 text-center text-sm text-foreground transition-colors hover:bg-foreground/5 sm:w-auto sm:py-2.5"
                >
                  Book a demo
                </a>
              </div>
            </div>
          </div>

          {/* The build demo, swapped in from /ai-app-builder. Its two cards
              are this page's two claims side by side — describe the work only
              your firm does, and watch it land live for the team and the
              client — which is the half of the headline the carousel of
              finished screens was not showing. */}
          <BuilderHeroVisual />
          {/* Credibility right under the product shot, before the argument
              starts. */}
          <PortalSocialProof />
        </div>
      </section>

      <div className="relative">
        <GridRails />
        <GridDivider fullBleed />

        <PortalProblem />
        <GridDivider />

        <PortalReadyMade />
        <GridDivider />

        {/* Three cards, not five. Describe, Plan, Build is the arc; Iterate
            and Secured were a fourth and fifth beat on a rail that then had to
            be stepped through to be seen at all. Nothing is lost by cutting
            them here — the "built by Assembly, never by the AI" claim the
            Secured card made has its own section further down this page
            (PortalTrust), where it is the heading rather than a footnote.

            Sliced from BUILD_STEPS rather than restated, so this page's
            captions cannot drift from the full set. */}
        <PortalBuild steps={BUILD_STEPS.slice(0, 3)} />
        <GridDivider />

        {/* No divider after this one: the segment grid closes on its own
            rule, which already runs rail to rail, and a second line below it
            read as a doubled break. */}
        <PortalTailor />

        {/* The claim about a firm's existing stack, which used to be a fifth
            card inside the grid above. No divider between them: the section
            draws its own rules, and a third line in the same inch read as a
            stutter. */}
        <PortalStack />

        <PortalTrust />
        <GridDivider />
      </div>

      <div className="relative">
        <GridRails />
        <PortalProof />
        <GridDivider />
        <PortalPricing />
        <GridDivider />
      </div>

      <div className="relative pb-10 md:pb-16">
        <GridRails />
        {/* Divided with dotted rules, as on the AI app builder page — and the
            same treatment the stack accordion further up this page already
            uses, so the two lists on one page read as one control. No short
            forms needed: every question here already sets on one line. */}
        <FAQ
          heading="Frequently asked questions"
          items={PORTAL_FAQS}
          variant="divided"
          dottedRules
        />
      </div>

      <div className="border-t border-border [[data-theme=dark]_&]:border-[#383838]" />

      <CTA
        heading={
          <>
            Build the client portal
            <br />
            only your firm could
          </>
        }
        // The free plan and the no-card point are both already made by the
        // pricing section further up this page, so the chips restated them.
        planChips={false}
      />
    </>
  );
}
