import type { Metadata } from "next";
import { CTA } from "@/components/home/cta";
import { FAQ, type FAQEntry } from "@/components/home/faq";
import { TrustTicker } from "@/components/home/trust-ticker";
import {
  Testimonials,
  type CustomerStory,
} from "@/components/home/testimonials";
import { SecurityCompliance } from "@/components/security/security-compliance";
import { GridDivider, GridRails } from "@/components/ui/grid-lines";
import { VisualSlot } from "@/components/ui/visual-slot";
import { PortalProblem } from "@/components/client-portal/portal-problem";
import { PortalReadyMade } from "@/components/client-portal/portal-ready-made";
import { PortalBuild } from "@/components/client-portal/portal-build";
import { PortalTailor } from "@/components/client-portal/portal-tailor";
import { PortalStack } from "@/components/client-portal/portal-stack";
import { PortalTrust } from "@/components/client-portal/portal-trust";
import { PortalPricing } from "@/components/client-portal/portal-pricing";
import { DEMO_URL, SIGNUP_URL } from "@/lib/constants";
import { PAGE_SEO, pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata(PAGE_SEO.clientPortal);

/**
 * Every question carries "client portal" for search, and every answer carries
 * the page's thesis: this is the portal you can build on. Earnest objections
 * first, the two search questions last.
 */
const PORTAL_FAQS: FAQEntry[] = [
  {
    question: "What is a client portal?",
    answer:
      "A client portal is a secure, branded hub where your clients message you, pay invoices, sign contracts, share files, and track work in one place. Assembly gives you those as ready-made apps you install in a click, then lets you build custom apps into the same portal.",
  },
  {
    question: "Can I build my own apps into it?",
    answer:
      "Yes. Describe the app you need in plain English. Assembly shows you a plan to approve or edit, then ships a real app into your portal with logins, permissions, branding, and payments already handled. Change it later the same way, by chatting.",
    links: [{ label: "in plain English", href: "/ai-app-builder" }],
  },
  {
    question: "Do I need to code to customize it?",
    answer:
      "No. There is nothing to code. You describe what you want, review a plan, and publish. You can also start from 20+ ready-made templates, each a working app, and tell the builder what to change.",
    links: [{ label: "20+ ready-made templates", href: "/templates" }],
  },
  {
    question: "Can I white-label it?",
    answer:
      "Yes. Your logo and colors are on every plan. On Pro and up, clients sign in on your own domain with the Assembly badge removed, so the whole experience feels like your firm's software. Every new app you build inherits the brand automatically.",
  },
  {
    question: "Is my client portal secure?",
    answer:
      "Yes. Logins, permissions, and data isolation are platform infrastructure maintained by Assembly, never generated by AI. Assembly is SOC 2 Type II certified and GDPR and CCPA aligned, clients sign in with a secure email link or Google, and each app runs in its own sandboxed database.",
    links: [{ label: "SOC 2 Type II certified", href: "/security" }],
  },
  {
    question: "Is there a HIPAA-compliant portal?",
    answer:
      "Assembly supports HIPAA with a BAA on the Advanced plan. Ready-made apps like secure messaging, files, and contracts can handle PHI as long as the app does not use AI. Apps built with the AI app builder are not HIPAA-covered, because the build uses AI. Talk to us and we will map what fits.",
    links: [{ label: "Talk to us", href: DEMO_URL }],
  },
  {
    question: "The best client portal for service firms?",
    answer:
      "The best client portal is the one clients actually log in to, and the one your firm does not have to settle for. Assembly combines ready-made messaging, billing, files, contracts, forms, and tasks with an AI app builder, so agencies, accountants, consultants, and coaches get the essentials on day one and the custom apps only their firm needs.",
  },
  {
    question: "What is it not good for?",
    answer:
      "Public marketing websites. Assembly builds authenticated experiences for your team and your logged-in clients. A public site is better built elsewhere and linked from inside your portal.",
  },
];

/**
 * Collective CPA leads here rather than AdvertAI (which leads the builder and
 * comparison pages): the quote is this page's thesis in a customer's own words,
 * and accounting is the slower-converting, safety-first segment this page most
 * needs to reach. Already public on /customers, so nothing waits on approval.
 */
const COLLECTIVE_CPA: CustomerStory = {
  // Trimmed to the clause that is this page's thesis. The rest of the public
  // quote ("uniting elements of their technology with existing core
  // applications") is what the third stat already says.
  quote:
    "Assembly was the only one that let us flexibly build our own version of a client portal.",
  name: "Kyle Pearson",
  firm: "Collective CPA",
  image: "/images/customers/collective-cpa.jpg",
  // Short values, the way the component's bars are set: the figure carries the
  // claim and the caption only says what it counts.
  stats: [
    { value: "Under an hour", label: "To a live team dashboard" },
    { value: "One portal", label: "Ready-made and custom apps" },
    { value: "Zero", label: "Core applications replaced" },
  ],
  href: "/customers/collective-cpa",
};

export default function ClientPortalPage() {
  return (
    <>
      {/* Hero — the category the visitor searched for, and the thesis, in one
          breath. "Build on" is the one phrase no legacy portal (no builder) and
          no code-generation tool (no portal) can claim. */}
      <section className="px-6 pb-16 pt-24 text-center md:pb-24 md:pt-32">
        <div className="mx-auto max-w-3xl">
          {/* The site's shared chip, same one the stat and filter chips use.
              The plan is the first thing this visitor wants to know, so it
              leads rather than trailing the buttons. */}
          <span className="inline-flex items-center rounded-md bg-muted px-3 py-1.5 font-mono text-xs uppercase tracking-wide text-muted-foreground">
            Free forever plan
          </span>
          <h1 className="type-display mt-6 text-balance">
            The client portal you can build on.
          </h1>
          <p className="type-lead mx-auto mt-6 max-w-xl text-balance text-muted-foreground">
            Assembly is the client portal with ready-made apps for messaging,
            billing, files, and contracts, plus an AI app builder to customize
            your own.
          </p>
          <div className="mx-auto mt-8 flex w-full max-w-xs flex-col items-stretch gap-3 sm:w-auto sm:max-w-none sm:flex-row sm:items-center sm:justify-center">
            <a
              href={SIGNUP_URL}
              className="rounded-lg bg-foreground px-5 py-2.5 text-center text-sm text-background transition-opacity hover:opacity-90"
            >
              Get started free
            </a>
            <a
              href={DEMO_URL}
              className="rounded-lg border border-foreground/20 bg-transparent px-5 py-2.5 text-center text-sm text-foreground transition-colors hover:bg-foreground/5"
            >
              Book a demo
            </a>
          </div>
        </div>

        <div className="mx-auto mt-14 max-w-[1200px] px-0 md:px-4">
          <VisualSlot
            className="text-left"
            label="Hero shot, also the OG image"
            description="Left third: a prompt box in Assembly's build panel reading Build a client onboarding tracker my clients can see, with a Plan card already surfaced and an Approve button. Right two-thirds: a laptop frame showing the Brandmages client portal on its own domain, sidebar listing Home, Messages, Billing, Files, Project Tracker and Approvals, with a new Onboarding item mid-slide into the sidebar. A thin line connects the Approve button to the new item. The portal is the hero; the AI is subordinate to it."
          />
        </div>
      </section>

      {/* Credibility before the argument starts. The site's own numbers band,
          rather than a second one with different figures — the brief's stats
          and this band's disagree, and that is a fact-check to settle once, in
          one place, not a reason for the page to state its own. */}
      <div className="border-t border-border [[data-theme=dark]_&]:border-[#383838]" />
      <TrustTicker />

      <div className="relative">
        <GridRails />
        <GridDivider fullBleed />

        <PortalProblem />
        <GridDivider />

        <PortalReadyMade />
        <GridDivider />

        <PortalBuild />
        <GridDivider />

        <PortalTailor />
        <GridDivider />

        <PortalStack />
        <GridDivider />

        <PortalTrust />
        <GridDivider />
      </div>

      {/* The seals sit under the trust section's argument, the way they do on
          the security page. */}
      <SecurityCompliance />
      <div className="border-t border-border [[data-theme=dark]_&]:border-[#383838]" />

      <div className="relative">
        <GridRails />
        <Testimonials story={COLLECTIVE_CPA} />
        <GridDivider />
        <PortalPricing />
        <GridDivider />
      </div>

      <div className="relative pb-10 md:pb-16">
        <GridRails />
        <FAQ heading="Frequently asked questions" items={PORTAL_FAQS} twoColumn />
      </div>

      <div className="border-t border-border [[data-theme=dark]_&]:border-[#383838]" />

      <CTA
        heading={
          <>
            Build the client portal
            <br />
            only your firm could
          </>
        }
      />
    </>
  );
}
