"use client";

// ─────────────────────────────────────────────────────────────────────────
// UNIFIED PLATFORM — the overview of what makes Assembly different.
// A vertical tab tour: four steps on the left (foundation, ready-made apps, app
// builder, security), each revealing its callout copy and lighting up the
// matching region in the client-portal mock on the right. It auto-advances
// and loops; clicking/hovering a step — or a region in the mock — jumps to it.
// ─────────────────────────────────────────────────────────────────────────

import { useEffect, useRef, useState } from "react";
import { IconBrandMark } from "@/components/home/mock-icons";

// The section heading and body are placeholders: the PRD gives copy for the
// four tabs, not for the header.
const HEADING = "Everything your firm runs on, in one place";
const BODY =
  "A CRM for your team, a branded client experience, 30+ ready-made apps, and an AI app builder for everything else.";

// Active-region highlight — a quiet surface fill (the sidebar/URL step up a
// notch when their step is active). No outline, no ring.
const HL_SIDEBAR_BG = "var(--mk-elevated)";
const HL_PILL_BG = "var(--mk-fill)";

// Order is the tour's order, building from the foundation up. Only the first
// two steps have a region in the mock; the builder and security steps read as
// copy in the step list and light nothing until they get visuals of their own.
const REGIONS = [
  {
    id: "url",
    tag: "Foundation",
    header: "Built-in CRM and client experience",
    body: "Contacts and companies live in one CRM. Clients get a branded experience on your domain to message your team, share files, sign contracts, pay, and more.",
  },
  {
    id: "sidebar",
    tag: "Ready-made apps",
    header: "30+ ready-made apps",
    body: "Assembly includes apps for intake, onboarding, proposals, payments, project tracking, and more, and each app can be remixed to fit what you want.",
  },
  {
    id: "builder",
    tag: "App builder",
    header: "Build anything else with AI",
    body: "Describe what you need, approve the plan, and AI builds it into your workspace with sign-in, permissions, and branding already handled.",
  },
  {
    id: "avatar",
    tag: "Security",
    header: "Enterprise-grade security",
    body: "Sign-in, permissions, and data isolation are platform infrastructure, never generated by AI. Every app runs in its own sandbox. SOC 2 Type II certified.",
  },
] as const;

// How long each step holds before the tour auto-advances to the next region.
// Unhurried so the longer copy has time to read.
const DWELL_MS = 6500;

type RegionId = (typeof REGIONS)[number]["id"];

const APPS = [
  "Onboarding",
  "Time tracker",
  "Invoices",
  "Documents",
  "Messages",
];
const ACTIVE_APP = "Time tracker";
// On a phone the mock is cropped to a fraction of its width and only ~300px of
// its height shows, so the full list crowds the sidebar and the rows at the foot
// get cut mid-word. Three apps still make the point the section is about — a
// sidebar with several apps in it, one of them open.
const MOBILE_APPS = new Set(["Onboarding", "Time tracker", "Messages"]);

const ENTRIES = [
  {
    desc: "Discovery call",
    client: "Novatech",
    dur: "0h 45m",
    status: "Pending",
  },
  {
    desc: "Q1 financial review",
    client: "Meridian",
    dur: "3h 45m",
    status: "Approved",
  },
  {
    desc: "Reconcile accounts",
    client: "Oakwood",
    dur: "2h 15m",
    status: "Approved",
  },
  {
    desc: "Payroll processing",
    client: "Bloom",
    dur: "4h 00m",
    status: "Logged",
  },
  {
    desc: "Client onboarding call",
    client: "Northwind",
    dur: "1h 15m",
    status: "Approved",
  },
  {
    desc: "Contract review",
    client: "Vertex",
    dur: "0h 30m",
    status: "Pending",
  },
  {
    desc: "Monthly bookkeeping",
    client: "Harbor",
    dur: "5h 30m",
    status: "Approved",
  },
  {
    desc: "Invoice preparation",
    client: "Cedar & Co",
    dur: "1h 00m",
    status: "Pending",
  },
  {
    desc: "Year-end tax filing",
    client: "Summit Group",
    dur: "6h 15m",
    status: "Approved",
  },
] as const;

// Reuse the site's theme-aware mock-pill tokens so pills adapt in dark mode
// alongside the rest of the mock (see --mock-* in globals.css).
const STATUS_STYLES: Record<string, string> = {
  Approved: "bg-[var(--mock-positive-bg)] text-[var(--mock-positive-fg)]",
  Pending: "bg-[var(--mock-warning-bg)] text-[var(--mock-warning-fg)]",
  Logged: "bg-[var(--mk-fill)] text-[var(--mk-muted)]",
};

// Description is the only flexible column, so it soaks up every spare pixel and
// pushes Client/Duration out toward the cut. Wider trailing columns shrink it and
// pull those two back in.
const COLS =
  "grid grid-cols-[minmax(0,1fr)_112px_88px_74px] items-center gap-3";

// Real filled icons supplied as SVGs (clipboard, alarm-clock, pen, file,
// comment), mapped to the sidebar apps. Coloured via `fill`.
const APP_ICONS: Record<string, { w: number; h: number; d: string }> = {
  Onboarding: {
    w: 15,
    h: 20,
    d: "M9.0625 3.75H5.9375C5.41797 3.75 5 3.33203 5 2.8125C5 2.29297 5.41797 1.875 5.9375 1.875H9.0625C9.58203 1.875 10 2.29297 10 2.8125C10 3.33203 9.58203 3.75 9.0625 3.75ZM9.0625 5.625C10.5117 5.625 11.7031 4.53125 11.8594 3.125H12.5C12.8438 3.125 13.125 3.40625 13.125 3.75V17.5C13.125 17.8438 12.8438 18.125 12.5 18.125H2.5C2.15625 18.125 1.875 17.8438 1.875 17.5V3.75C1.875 3.40625 2.15625 3.125 2.5 3.125H3.14063C3.29688 4.53125 4.48828 5.625 5.9375 5.625H9.0625ZM11.4023 1.25C10.8984 0.496094 10.0391 0 9.0625 0H5.9375C4.96094 0 4.10156 0.496094 3.59766 1.25H2.5C1.12109 1.25 0 2.37109 0 3.75V17.5C0 18.8789 1.12109 20 2.5 20H12.5C13.8789 20 15 18.8789 15 17.5V3.75C15 2.37109 13.8789 1.25 12.5 1.25H11.4023Z",
  },
  "Time tracker": {
    w: 20,
    h: 20,
    d: "M15.7266 1.96094C15.5156 2.02734 15.2852 2.03125 15.0937 1.92578C14.8672 1.80078 14.6328 1.68359 14.3984 1.57813C13.9922 1.39453 13.8633 0.863281 14.2383 0.617188C14.8242 0.230469 15.5273 0.00390625 16.2812 0.00390625C18.3359 0.00390625 20 1.66797 20 3.72266C20 4.23828 19.8945 4.73047 19.7031 5.17969C19.5273 5.58984 18.9844 5.5625 18.7305 5.19531C18.582 4.98047 18.4258 4.77344 18.2617 4.57031C18.125 4.39844 18.0859 4.17187 18.1133 3.95312C18.1211 3.87891 18.1289 3.80078 18.1289 3.72266C18.1289 2.70313 17.3008 1.87891 16.2852 1.87891C16.0937 1.87891 15.9063 1.91016 15.7305 1.96484L15.7266 1.96094ZM1.26953 5.19141C1.01562 5.55859 0.46875 5.58594 0.296875 5.17578C0.105469 4.72656 0 4.23437 0 3.71875C0 1.66406 1.66406 0 3.71875 0C4.47266 0 5.17578 0.226563 5.76172 0.613281C6.13672 0.859375 6.00781 1.39062 5.60156 1.57422C5.36328 1.68359 5.13281 1.79688 4.90625 1.92188C4.71484 2.02734 4.48047 2.02344 4.27344 1.95703C4.09766 1.90234 3.91406 1.87109 3.71875 1.87109C2.69922 1.87109 1.875 2.69922 1.875 3.71484C1.875 3.79297 1.87891 3.87109 1.89063 3.94531C1.91797 4.16406 1.87891 4.39063 1.74219 4.5625C1.57812 4.76563 1.42187 4.97266 1.27344 5.1875L1.26953 5.19141ZM16.875 11.25C16.875 9.42664 16.1507 7.67795 14.8614 6.38864C13.572 5.09933 11.8234 4.375 10 4.375C8.17664 4.375 6.42795 5.09933 5.13864 6.38864C3.84933 7.67795 3.125 9.42664 3.125 11.25C3.125 13.0734 3.84933 14.822 5.13864 16.1114C6.42795 17.4007 8.17664 18.125 10 18.125C11.8234 18.125 13.572 17.4007 14.8614 16.1114C16.1507 14.822 16.875 13.0734 16.875 11.25ZM15.4883 18.0664C13.9883 19.2734 12.0781 20 10 20C7.92187 20 6.01172 19.2734 4.51172 18.0664L2.85156 19.7266C2.48438 20.0937 1.89062 20.0937 1.52734 19.7266C1.16406 19.3594 1.16016 18.7656 1.52734 18.4023L3.1875 16.7422C1.97656 15.2383 1.25 13.3281 1.25 11.25C1.25 6.41797 5.16797 2.5 10 2.5C14.832 2.5 18.75 6.41797 18.75 11.25C18.75 13.3281 18.0234 15.2383 16.8164 16.7383L18.4766 18.3984C18.8437 18.7656 18.8437 19.3594 18.4766 19.7227C18.1094 20.0859 17.5156 20.0898 17.1523 19.7227L15.4922 18.0625L15.4883 18.0664ZM10.9375 7.1875V10.8633L12.5391 12.4648C12.9062 12.832 12.9062 13.4258 12.5391 13.7891C12.1719 14.1523 11.5781 14.1562 11.2148 13.7891L9.33984 11.9141C9.16406 11.7383 9.06641 11.5 9.06641 11.25V7.1875C9.06641 6.66797 9.48438 6.25 10.0039 6.25C10.5234 6.25 10.9414 6.66797 10.9414 7.1875H10.9375Z",
  },
  Invoices: {
    w: 20,
    h: 20,
    d: "M1.42175 13.8203C1.58191 13.25 1.88269 12.7305 2.30457 12.3086L13.7889 0.824219C14.3124 0.296875 15.0311 0 15.7811 0C16.5311 0 17.2499 0.296875 17.7772 0.828125L19.1718 2.22266C19.703 2.75 19.9999 3.46875 19.9999 4.21875C19.9999 4.96875 19.703 5.6875 19.1718 6.21484L7.68738 17.6992C7.26941 18.1172 6.74597 18.4219 6.17566 18.582L1.18738 19.9648C0.86316 20.0547 0.511598 19.9648 0.273316 19.7227C0.0350352 19.4805 -0.0587148 19.1328 0.031129 18.8086L1.42175 13.8203ZM15.1093 2.15234L13.0428 4.21875L15.7811 6.95703L17.8475 4.89062C18.0272 4.71094 18.1249 4.47266 18.1249 4.21875C18.1249 3.96484 18.0233 3.72656 17.8475 3.54687L16.453 2.15234C16.2733 1.97656 16.0311 1.875 15.7811 1.875C15.5311 1.875 15.2889 1.97656 15.1093 2.15234ZM11.7186 5.54297L3.62879 13.6367C3.43738 13.8281 3.30066 14.0625 3.22644 14.3242L2.28504 17.7187L5.67957 16.7773C5.93738 16.707 6.17566 16.5664 6.36707 16.375L14.4569 8.28125L11.7186 5.54297Z",
  },
  Documents: {
    w: 15,
    h: 20,
    d: "M6.875 1.875H2.5C2.15625 1.875 1.875 2.15625 1.875 2.5V17.5C1.875 17.8438 2.15625 18.125 2.5 18.125H12.5C12.8438 18.125 13.125 17.8438 13.125 17.5V8.125H9.6875C8.13281 8.125 6.875 6.86719 6.875 5.3125V1.875ZM12.3477 6.25L8.75 2.65234V5.3125C8.75 5.83203 9.16797 6.25 9.6875 6.25H12.3477ZM0 2.5C0 1.12109 1.12109 0 2.5 0H7.71484C8.37891 0 9.01563 0.261719 9.48438 0.730469L14.2695 5.51953C14.7383 5.98828 15 6.625 15 7.28906V17.5C15 18.8789 13.8789 20 12.5 20H2.5C1.12109 20 0 18.8789 0 17.5V2.5Z",
  },
  Messages: {
    w: 20,
    h: 20,
    d: "M2.02734 15.0352C0.753906 13.4609 0 11.5 0 9.375C0 4.19922 4.47656 0 10 0C15.5234 0 20 4.19922 20 9.375C20 14.5508 15.5234 18.75 10 18.75C8.57422 18.75 7.21875 18.4688 5.99219 17.9688L1.44531 19.918C1.30078 19.9805 1.15234 20 0.996094 20C0.445312 20 0 19.5547 0 19.0039C0 18.8359 0.0429687 18.6719 0.121094 18.5273L2.02734 15.0352ZM3.48437 13.8555C3.96094 14.4453 4.03516 15.2656 3.67188 15.9336L2.96875 17.2266L5.25391 16.2461C5.71484 16.0469 6.23828 16.043 6.70313 16.2344C7.70703 16.6445 8.82031 16.875 9.99609 16.875C14.5977 16.875 18.1211 13.4062 18.1211 9.375C18.1211 5.34375 14.6016 1.875 10 1.875C5.39844 1.875 1.875 5.34375 1.875 9.375C1.875 11.0469 2.46484 12.5938 3.48437 13.8555Z",
  },
};

// Sized to the 11px row label rather than above it, and centred in a fixed-width
// column: the glyphs have different aspect ratios, so letting each set its own
// width left the labels beside them starting at different x positions.
const APP_ICON_H = 11;
const APP_ICON_COL = 14;

function AppIcon({ name, color }: { name: string; color: string }) {
  const ic = APP_ICONS[name];
  const w = (APP_ICON_H * ic.w) / ic.h;
  return (
    <span
      className="flex shrink-0 items-center justify-center"
      style={{ width: APP_ICON_COL, height: APP_ICON_H }}
    >
      <svg
        width={w}
        height={APP_ICON_H}
        viewBox={`0 0 ${ic.w} ${ic.h}`}
        fill={color}
        aria-hidden
        className="shrink-0"
      >
        <path d={ic.d} />
      </svg>
    </span>
  );
}

// Module-level (never nested in the section) so nothing remounts on parent
// re-renders. `active` is driven by the vertical tab tour beside it; hovering a
// region also jumps the tour to it.
function ProductionGapVisual({
  active,
  setActive,
}: {
  active: RegionId;
  setActive: (id: RegionId) => void;
}) {
  return (
    // No shadow: the border alone separates the window from the blue frame, and
    // the drop shadow read as a heavy smudge along the bottom of the panel.
    <div className="production-mock relative w-full select-none overflow-hidden rounded-l-lg border-y border-l border-border bg-[var(--mk-surface)] md:rounded-l-2xl [font-family:var(--font-inter),system-ui,sans-serif]">
      {/* Browser top bar — same right-edge fade as the body (fades to the dark
          mock surface behind it, not the bezel), so the top bar cuts off too. */}
      <div className="production-cut-fade flex h-[44px] items-center gap-3 border-b border-[var(--mk-hairline)] px-4">
        <div className="flex gap-1.5">
          {[0, 1, 2].map((i) => (
            <span
              key={i}
              className="size-[9px] rounded-full bg-[var(--mk-dots)]"
            />
          ))}
        </div>
        {/* Region: the branded client URL */}
        <button
          type="button"
          onMouseEnter={() => setActive("url")}
          onFocus={() => setActive("url")}
          style={active === "url" ? { backgroundColor: HL_PILL_BG } : undefined}
          className="relative flex items-center gap-1.5 rounded-[4px] border border-[var(--mk-border)] px-2.5 py-1 text-[10px] leading-none text-[var(--mk-muted)] outline-none transition-colors duration-200"
        >
          {/* A placeholder domain rather than the sample firm's: addressed to
              the reader, it reads as "your domain goes here" instead of as a
              marketing site we built for someone. */}
          yourbrand.com
        </button>
      </div>

      {/* Body: sidebar + app content. Height follows the content (the table),
          and the sidebar stretches to match. A soft right-edge mask fades the
          content into the cut so it reads as "continues off-frame" rather than a
          hard chop (the top bar above is exempt, so the avatar stays crisp).
          `production-cut-bottom` adds the same treatment along the bottom on a
          phone, where the crop lands mid-row — and only here, since on the
          44px top bar a bottom fade would erase the bar itself. */}
      <div className="production-cut-fade production-cut-bottom flex items-stretch">
        {/* The sidebar column holds one region, the app list. The client
            sign-in step has no target in the mock by design — it reads as copy
            in the step list and lights nothing here. */}
        <div
          // A floor as well as a cap: at 22% of a narrow column the sidebar fell
          // to ~90px, where "Time tracker" wrapped onto two lines and the longer
          // labels ran out over the table beside them. overflow-hidden is the
          // backstop — nothing in here may cross into the content.
          //
          // The sidebar step's fill is painted here below md, not on the app-list
          // button: without flex-1 that button is only as tall as its rows, so the
          // lit region stopped short and left the rest of the column white. From
          // md up the button fills the column itself and owns the fill.
          // Below md the column is held to exactly the height the crop shows —
          // the blue box's 320px, less its 16px top padding, the mock's top
          // border, and the 44px browser bar — so the lit column ends at the cut
          // rather than ~190px below it. The body itself stays as tall as the
          // table, so nothing about the content crop changes.
          className={`relative flex h-[259px] w-[22%] min-w-[136px] max-w-[156px] shrink-0 flex-col overflow-hidden border-r border-[var(--mk-hairline)] transition-colors duration-200 md:h-auto ${
            active === "sidebar"
              ? "bg-[var(--mk-elevated)] md:bg-transparent"
              : ""
          }`}
        >
        {/* Region: the app sidebar */}
        <button
          type="button"
          onMouseEnter={() => setActive("sidebar")}
          onFocus={() => setActive("sidebar")}
          style={
            active === "sidebar"
              ? { backgroundColor: HL_SIDEBAR_BG }
              : undefined
          }
          // flex-1 from md up only: it fills the column so this button owns the
          // step's fill. Below md the parent paints it instead (see above).
          // outline-none with nothing in its place is deliberate: onFocus lights
          // this row to HL_SIDEBAR_BG (above), so focus already shows, and a ring
          // in the mock's ink read as a hard black box drawn over the artwork.
          className="flex flex-col gap-0.5 px-2 py-3 text-left shadow-none outline-none transition-colors duration-200 md:flex-1"
        >
          {/* px-2 matches the nav rows below, so the icon column shares one
              left edge down the whole sidebar. */}
          {/* 16px on an 8px gap, not 20 on 10: the mark sat well above the nav
              icons' weight, and its wider column pushed the workspace name 6px
              past where every label below it starts. These two numbers sum to
              the nav rows' own 14 + 10, so one text edge runs down the side. */}
          <div className="mb-2 flex items-center gap-2 px-2">
            <span className="flex size-4 shrink-0 items-center justify-center rounded-[3px] bg-[var(--mk-invert-bg)]">
              <IconBrandMark className="w-[9px] text-[var(--mk-invert-fg)]" />
            </span>
            {/* Generic, to match the placeholder domain in the URL bar — a named
                sample firm beside yourbrand.com read as two different tenants. */}
            <span className="truncate pb-[3px] -mb-[3px] text-[11px] text-[var(--mk-fg)]">
              Your brand
            </span>
          </div>
          {APPS.map((app) => {
            const on = app === ACTIVE_APP;
            const iconColor = on
              ? "var(--mk-icon-active)"
              : "var(--mk-icon-idle)";
            const labelCls = on
              ? "text-[var(--mk-fg)]"
              : "text-[var(--mk-muted)]";
            const rowBg = on ? "bg-[var(--mk-selected)]" : "";
            return (
              <span
                key={app}
                className={`flex items-center gap-2.5 rounded-[4px] px-2 py-1.5 text-[11px] leading-none ${rowBg} ${labelCls} ${
                  MOBILE_APPS.has(app) ? "" : "max-md:hidden"
                }`}
              >
                <AppIcon name={app} color={iconColor} />
                <span className="truncate pb-[3px] -mb-[3px]">{app}</span>
              </span>
            );
          })}
        </button>
        </div>

        {/* Main content — a polished Time tracker screen. Given a fixed width
            wider than the space it has, so it runs past the box's right edge and
            cuts off there (the top bar above keeps the avatar in view). */}
        <div className="relative w-[620px] shrink-0 overflow-hidden p-5">
          {/* Table toolbar — search + filters. No "Time tracker" title here; the
              sidebar already names the app, so this space does real work. */}
          <div className="flex items-center gap-2">
            {/* Search is capped rather than flex-1: the table is intentionally
                wider than the visible cut, so a full-width search pushed the
                Filters control past the clip and out of frame. */}
            <div className="flex min-w-0 max-w-[360px] flex-1 items-center gap-1.5 rounded-[4px] border border-[var(--mk-border)] px-2.5 py-[7px] text-[10px] leading-none text-[var(--mk-subtle)]">
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                aria-hidden
                className="size-[12px] shrink-0"
              >
                <circle cx="11" cy="11" r="7" />
                <path d="m20 20-3-3" />
              </svg>
              Search entries
            </div>
            {/* Filters — the single control beside search; the date/client
                chips that used to sit here crowded the toolbar. */}
            <span className="flex shrink-0 items-center gap-1 rounded-[4px] border border-[var(--mk-border)] px-2.5 py-[7px] text-[10px] leading-none text-[var(--mk-muted)]">
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                aria-hidden
                className="size-[11px]"
              >
                <path d="M3 6h18M6 12h12M10 18h4" />
              </svg>
              Filters
            </span>
          </div>

          <div className="mt-3 overflow-hidden rounded-[4px] border border-[var(--mk-border)]">
            <div
              className={`${COLS} border-b border-[var(--mk-hairline)] bg-[var(--mk-elevated)] px-3 py-2 text-[9px] leading-none text-[var(--mk-subtle)]`}
            >
              <span>Description</span>
              <span>Client</span>
              <span>Duration</span>
              <span>Status</span>
            </div>
            {ENTRIES.map((e, i) => (
              <div
                key={e.desc}
                className={`${COLS} px-3 py-2.5 text-[11px] leading-none ${
                  i < ENTRIES.length - 1
                    ? "border-b border-[var(--mk-hairline)]"
                    : ""
                }`}
              >
                <span className="truncate pb-[3px] -mb-[3px] text-[var(--mk-fg-2)]">
                  {e.desc}
                </span>
                <span className="truncate pb-[3px] -mb-[3px] text-[var(--mk-muted)]">
                  {e.client}
                </span>
                <span className="tabular-nums text-[var(--mk-muted)]">
                  {e.dur}
                </span>
                <span>
                  <span
                    className={`inline-flex rounded-full px-2 py-1 text-[9px] leading-none ${STATUS_STYLES[e.status]}`}
                  >
                    {e.status}
                  </span>
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Light-mode-only soft edge at the cut. Dark mode fades the content into
          its dark surface (the mask), but in light that just washes into white —
          so light instead gets a faint shadow, reading as content continuing
          under an edge. */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 right-0 hidden w-20 md:block [[data-theme=dark]_&]:hidden"
        style={{
          background:
            "linear-gradient(to right, transparent, color-mix(in srgb, var(--mk-fg) 5%, transparent))",
        }}
      />
      {/* On a phone the mock is stacked and its cut is the thing you notice, so
          it gets the same weight the how-it-works phone screens give their
          bottom cut — that inset shadow turned to the right edge, rather than
          the 5% wash above. Both sections then read as content passing under an
          edge instead of stopping at one. */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 md:hidden [[data-theme=dark]_&]:hidden"
        style={{ boxShadow: "inset -22px 0 18px -14px rgba(16,24,40,0.16)" }}
      />
    </div>
  );
}

// The whole interactive section: a vertical tab list on the left whose active
// step both reveals its callout copy and lights up the matching region in the
// mock on the right. It auto-advances through the three regions and loops;
// clicking or hovering a tab (or a region in the mock) jumps the tour there.
// Progress is painted imperatively (refs) so the loop never re-renders the mock.
function ProductionGapExplorer() {
  const [active, setActive] = useState(0);

  // Refs so the rAF loop reads state without re-subscribing, and the per-tab
  // progress rails can be painted directly (no per-frame React render).
  const activeRef = useRef(0);
  const progressRef = useRef(0);
  const fillRefs = useRef<(HTMLSpanElement | null)[]>([]);
  const rootRef = useRef<HTMLDivElement>(null);
  const onScreenRef = useRef(true);

  useEffect(() => {
    activeRef.current = active;
  }, [active]);

  const paint = () => {
    fillRefs.current.forEach((el, idx) => {
      if (!el) return;
      const p = idx === activeRef.current ? progressRef.current : 0;
      el.style.transform = `scaleX(${p})`;
    });
  };

  // Jump to a step and restart its dwell. Landing on the step that is already
  // running is a no-op: the mock's regions activate on mouseenter, so sweeping
  // out of a region and back in fired this again and visibly restarted a rail
  // that was halfway across.
  //
  // Deliberately no pause-on-hover to go with it. Hovering a region is how you
  // SELECT it here, so freezing the clock at the same time left the rail you
  // just lit sitting at zero for as long as the pointer stayed there — which
  // reads as the animation being broken, not as a considered pause.
  const activate = (i: number) => {
    if (i === activeRef.current) return;
    activeRef.current = i;
    progressRef.current = 0;
    paint();
    setActive(i);
  };
  const activateId = (id: RegionId) =>
    activate(REGIONS.findIndex((r) => r.id === id));

  useEffect(() => {
    const reduce = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;
    if (reduce) return; // no auto-advance; tabs still switch on click

    // Only run the clock while the section is on screen — browsers throttle rAF
    // offscreen, which would desync the progress rail (same fix as How it works).
    const el = rootRef.current;
    let io: IntersectionObserver | undefined;
    if (el && "IntersectionObserver" in window) {
      io = new IntersectionObserver(
        ([entry]) => {
          onScreenRef.current = entry.isIntersecting;
        },
        { threshold: 0 },
      );
      io.observe(el);
    }

    let raf = 0;
    let last = 0;
    const tick = (ts: number) => {
      const running = onScreenRef.current && !document.hidden;
      if (!running) {
        last = 0; // resume with a fresh delta instead of one big leap
      } else {
        if (!last) last = ts;
        const dt = Math.min(ts - last, 64); // clamp throttled gaps
        last = ts;
        progressRef.current += dt / DWELL_MS;
        if (progressRef.current >= 1) {
          progressRef.current = 0;
          const next = (activeRef.current + 1) % REGIONS.length;
          activeRef.current = next;
          setActive(next);
        }
      }
      paint();
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(raf);
      io?.disconnect();
    };
  }, []);

  return (
    <div
      ref={rootRef}
      // No frame, fill, or column divider — the tab hairlines and the blue
      // visual carry the structure on their own. The column gap matches the
      // section header's, since there's no longer a divider to sit between them.
      className="grid md:grid-cols-[minmax(0,330px)_minmax(0,1fr)] md:items-stretch md:gap-x-12"
    >
      {/* Left — vertical tabs; the active one expands its copy. */}
      <div
        role="tablist"
        aria-orientation="vertical"
        aria-label="What ships with every app"
        className="order-2 flex flex-col pb-5 md:order-none md:pb-6"
      >
        {REGIONS.map((r, i) => {
          const on = i === active;
          return (
            <button
              key={r.id}
              type="button"
              role="tab"
              aria-selected={on}
              // Click (or keyboard focus) only — on hover, the panel changed
              // under the pointer on the way past it, which reads as the page
              // twitching rather than as a control being used. The autoplay
              // still advances it on its own.
              onClick={() => activate(i)}
              onFocus={() => activate(i)}
              // No horizontal inset: with the frame gone the copy aligns to the
              // section heading above instead of sitting inside a phantom edge.
              className="group relative border-t border-border py-5 pr-5 text-left outline-none first:border-t-0 focus-visible:bg-foreground/[0.03] md:pr-8 [[data-theme=dark]_&]:border-white/15"
            >
              {/* Top-edge rail that fills left→right over the dwell on the
                  active tab. -top-px, not top-0: absolute offsets resolve against
                  the padding box, which begins inside the 1px border-t, so top-0
                  parked the fill one pixel BELOW the gray hairline instead of
                  covering it. */}
              <span
                aria-hidden
                className="absolute inset-x-0 -top-px z-10 h-px overflow-hidden group-first:top-0"
              >
                {/* Every other step rides on its own border-t, but the first has
                    that removed, so its rail ran across nothing and the unfilled
                    remainder simply wasn't there. Mobile only for now. */}
                {i === 0 && (
                  <span className="absolute inset-0 bg-border md:hidden [[data-theme=dark]_&]:bg-white/15" />
                )}
                <span
                  ref={(el) => {
                    fillRefs.current[i] = el;
                  }}
                  className="relative block h-full w-full origin-left bg-foreground"
                  style={{ transform: "scaleX(0)" }}
                />
              </span>

              <span
                className={`block [font-family:var(--font-diatype-mono)] text-[11px] uppercase tracking-[0.08em] ${
                  on ? "text-muted-foreground" : "text-muted-foreground/50"
                }`}
              >
                {r.tag}
              </span>

              <p
                className={`mt-1.5 text-[17px] leading-snug transition-colors ${
                  on
                    ? "text-foreground"
                    : "text-muted-foreground group-hover:text-foreground"
                }`}
              >
                {r.header}
              </p>

              {/* Body — revealed only for the active step (smooth height). */}
              <div
                className={`grid transition-all duration-300 ease-out ${
                  on
                    ? "mt-2 grid-rows-[1fr] opacity-100"
                    : "grid-rows-[0fr] opacity-0"
                }`}
              >
                <p className="overflow-hidden text-pretty text-sm leading-relaxed text-muted-foreground">
                  {r.body}
                </p>
              </div>
            </button>
          );
        })}
      </div>

      {/* The brand-blue box, rounded on every side. It has no right padding, so
          the app content runs to the box's right edge and cuts off there; the
          browser chrome (URL + avatar) spans the full width, so the top-right
          avatar stays in view even though the table bleeds off.
          On mobile it leads (the step list below reads as its legend) and the
          mock is laid out at a desktop width and scaled down to fit, rather than
          squeezed into a phone column where the sidebar and table would collapse
          into unreadable slivers. */}
      {/* min-w-0: the mock's sidebar and table have hard minimums (~750px), so
          without it the grid item takes the mock's min-content width and the
          blue box runs off the phone's right edge instead of ending at the
          section gutter. */}
      <div className="order-1 mb-8 flex min-w-0 self-stretch md:order-none md:mb-0">
        {/* Hairline below md only: the mock is laid out at desktop width and
            clipped by this box, so at phone widths its white surface reaches
            the box's right edge and meets the white page with nothing between
            them. From md up the box has room to show blue on every side. */}
        {/* The mock overflows this box on a phone and is clipped at its edge, so
            THIS radius is what shapes the crop's bottom corners — the mock's own
            bottom-left round sits well below the cut and never shows. One value
            all the way round on a phone: the wider bottom pair it used to carry
            made the crop read as a rounded tray under a squarer window. */}
        <div className="h-[320px] w-full min-w-0 overflow-hidden rounded-xl bg-[#7DA4FF] py-4 pl-4 ring-1 ring-black/[0.08] md:h-auto md:py-7 md:pl-7 md:ring-0">
          {/* The mock is a desktop layout — the sidebar and the table are
              percentages of a wide viewport, so at phone width they collapse
              into each other. It's laid out at a desktop width and cropped by
              the box instead, the same right-edge crop the design already uses
              on desktop, and the box is height-capped so it reads as a landscape
              window rather than a tall column. */}
          <div className="w-[760px] md:w-auto">
            <ProductionGapVisual
              active={REGIONS[active].id}
              setActive={activateId}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export function ProductionGap() {
  return (
    <section id="production-gap" className="py-16 md:py-24">
      <div className="mx-auto max-w-[1600px] px-6 md:px-10">
        {/* Header — left-aligned: heading (left) and body (right) sharing a
            row. */}
        <div className="mx-auto max-w-[1100px]">
          <div className="grid gap-y-5 md:grid-cols-2 md:items-start md:gap-x-12">
            {/* Balanced: unbalanced, this heading left "part" alone on a second
                line at phone widths. No effect on desktop, where it fits one. */}
            <h2 className="type-h2 max-w-lg text-balance text-foreground">
              {HEADING}
            </h2>
            <p className="type-lead max-w-lg text-pretty text-muted-foreground">
              {BODY}
            </p>
          </div>
        </div>

        {/* Product mock (desktop) with a description + hoverable region list
            below — the list is the whole interaction on mobile. */}
        <div className="mx-auto mt-12 max-w-[1100px] md:mt-16">
          <ProductionGapExplorer />
        </div>
      </div>
    </section>
  );
}
